### ISSUE TITLE
Should support changing elemMods in runtime

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#111]
There is a test for changing `mods` in runtime (https://github.com/bem/bem-xjst/blob/master/test/runtime-test.js#L221) but same thing fails for `elemMods`. So this test 
```js
it('should support changing elemMods in runtime', function() {
      test(function() {
        block('b1').elem('e1').def()(function() {
          this.elemMods.a = 'b';
          return applyNext();
        });
      }, {
        block: 'b1',
        content: { elem: 'e1' }
      }, '<div class="b1"><div class="b1__e1 b1__e1_a_b"</div>');
    });
```
will fail with `AssertionError: '<div class="b1"><div class="b1__e1"></div></div>' deepEqual '<div class="b1"><div class="b1__e1 b1__e1_a_b"</div>'`.

**Comment by zxqfox** [comment]
Take a look pleasee?

/cc @indutny @veged

**Comment by veged** [comment]
looks ok
