### ISSUE TITLE
No runtime in production mode

### ISSUE THREAD

**Issue by apsavin** [bem/bem-xjst#127]
version: 0.9.0
When I use option `optimize: true`, I get the optimized version, but without runtime (no functions like `applyNext`), so nothing works.
What can be the cause?

**Comment by tadatuta** [comment]
I think `v1.2.1` should be compatible with 0.9.0. Can you please check minimization there?

**Comment by arikon** [comment]
@apsavin Please reopen if it still reproduced in 1.2.1.

**Comment by tadatuta** [comment]
And please tell why do you need it?
