### ISSUE TITLE
Wildcard match on elem should be overridable

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#131]
For BEMJSON
```js
({
    block: 'button',
    content: [
        {
            elem: 'e1'
        },
        {
            elem: 'e2'
        }
    ]
});
```
with templates
```js
block('button')(
    elem('*')(
        tag()('span')
    ),
    elem('e2')(
        tag()('blah')
    )
)
```
the result is
```html
<div class="button"><span class="button__e1"></span><span class="button__e2"></span>
</div>
```
but
```html
<div class="button"><span class="button__e1"></span><blah class="button__e2"></blah>
</div>
```
expected.

**Comment by indutny** [comment]
Nope, this won't work :) Wildcard is supposed to be run before every non-wildcard template.

**Comment by zxqfox** [comment]
But why? Can you link me to the talk about this decision?

**Comment by indutny** [comment]
@zxqfox performance. I and @veged have talked about this offline.

**Comment by zxqfox** [comment]
@indutny I mean, why before? There are cases when we can call this matcher as usual, Not really sure why it (`'*'`) can be slower that any other matcher.

**Comment by indutny** [comment]
@zxqfox what kind of cases do you mean?

`elem('*')` is not a regular matcher. Instead of going through all templates as we did in old bem-xjst, now we lookup `block+elem` key in a hashmap. Obviously this is what affected the way wildcard elements and blocks are implemented right now.

**Comment by zxqfox** [comment]
Well, at the point of template writer it looks like magic because he don't see any `before` keyword. Not sure that it's right. And I'm not sure that it's hard to change.

Can we rethink this if I'll find a way to fix that without performance decrease.

**Comment by veged** [comment]
It's okay without `before` keyword by following principle «from the general to the particular». Also, as I know, it doesn't affect any real cases.

**Comment by zxqfox** [comment]
It does, as I know.

We can't differentiate these atm:
```js
block('a').content()(
  elem('*')(function(){ return '1' + (applyNext()||''); }),
  elem('el')(function(){ return '2' + (applyNext()||''); }),
  elem('*')(function(){ return '3' + (applyNext()||''); }),
  elem('el')(function(){ return '4' + (applyNext()||''); })
);
```
and the output for `{block: 'a', elem: 'el'}` is
```js
<div class="a__el">3142</div>
```

This actually means we can't use `elem('*')` and `elemMatch` atm on levels at all because it works like `!important` flag.

And there is code almost like this in our codebase ;-(
```js
block(...).def()(
  elemMatch(function(){ return this.elem; })(''),
  elem('1')('1'),
  elem('2')('2')
);
```

I'm not sure about this concrete case, but feels like we shouldn't be adamant.

**Comment by veged** [comment]
...**real** cases... ;-)
