### ISSUE TITLE
Multiple elems for the same templates

### ISSUE THREAD

**Issue by vithar** [bem/bem-xjst#138]
I have this code in my project:

```js
block('regions')(
    elem('region')(
        tag()('span'),
        match(function() { return this.ctx.url; })(
            tag()('a'),
            attrs()(function() { return { href: this.ctx.url }; })
        )
    ),
    elem('currency')(
        tag()('span'),
        match(function() { return this.ctx.url; })(
            tag()('a'),
            attrs()(function() { return { href: this.ctx.url }; })
        )
    )
);
```

As you can see, templates for `region` and `currency` element the same. Can we implement support for multiple arguments in `elem` (e.g. elem('region', 'currency')) or ability to pass array as argument (e.g. elem(['region', 'currency']))?

**Comment by tadatuta** [comment]
@vithar  see https://github.com/bem/bem-xjst/issues/135

**Comment by blond** [comment]
@tadatuta why not make multi-selectors like in CSS with `,` delimiters?

For elems:

```js
block('regions')(
    elems('region', 'currency')(
    )
)
```

For blocks:

```js
blocks('regions', 'smegions')(
)
```

**Comment by vithar** [comment]
+1

**Comment by miripiruni** [comment]
@vithar take a look at https://github.com/bem/bem-xjst/pull/165 

Isn't enough `elemMatch()`?

**Comment by vithar** [comment]
It is enough, thanks.

**Comment by blond** [comment]
So, what about multi-selectors?

**Comment by tadatuta** [comment]
@blond that's too rear case to provide such sugar

**Comment by blond** [comment]
@tadatuta, sugar affects performance?

**Comment by tadatuta** [comment]
it extends API without necessity
