### ISSUE TITLE
Implement syntax sugar to extend attrs

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-xjst#139]
Moved from https://github.com/bem/bem-core/issues/1221

Now:
```js
block('b1').attrs()(function() {
    return this.extend(applyNext(), { a: 'b' })
});
```

Can be wrapped with `block('b1').extendAttrs()({ a: 'b' })`.

**Comment by indutny** [comment]
Out of curiosity, is it this pattern that common?

**Comment by voischev** [comment]
Давайте сахар тогда для всего добавлять?

Может? ;)
```
block('b1').attrs()(() => this.extend(applyNext(), { a: 'b' }));
```
this тут правильно отработает?

**Comment by zxqfox** [comment]
@voischev Нет, не отработает правильно.

Guess, we can add special `.extend` mode for such purpose:
```js
block('qwe').any().extend()({disabled: true});
block('qwe').mix().extend()({block: 'yolo'});
```

**Comment by voischev** [comment]
@zxqfox :+1:

**Comment by miripiruni** [comment]
https://github.com/bem/bem-xjst/releases/tag/v8.0.0
