### ISSUE TITLE
BEMTREE: return `true` as is

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#145]
For `BEMTREE.apply({ block: 'b1', content: true })` got `{ block: 'b1', content: '' }` but `{ block: 'b1', content: true }` expected.

**Comment by zxqfox** [comment]
Guess it's because `.def` mode should return a String.
Not sure why you need to pass non-string scalar to content.

**Comment by tadatuta** [comment]
@zxqfox the issue is about BEMTREE ;)
