### ISSUE TITLE
Do not execute nested match if outer one is falsy

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#146]
E.g. for
```js
block('bla')(
    tag()('span'),
    match(function() { return this.ctx.d; })( // this.ctx.d is undefined
        tag()('a'),
        attrs()(match(function() { return this.ctx.d.a; })(function(){ // this will throw error
            return { f: 1 };
        }))
    )
) 
```

cc @indutny @veged @belyanskii

**Comment by veged** [comment]
semantically there is no such thing as "nested match" — they are all same level and order of execution is not guaranteed

**Comment by tadatuta** [comment]
Such code worked properly on `1.x` so we should at least try to fix it or maybe support it on convertor side.

**Comment by veged** [comment]
@indutny could we at least support preserving order of `.match`es execution?
