### ISSUE TITLE
Expose classBuilder

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#151]
Now `classBuilder` is available via `this._bemxjst.classBuilder.build(this.block, this.elem)` in templates.
I suggest to expose it to `this`.

// cc @veged

**Comment by veged** [comment]
sounds reasonable — what API do you suggest?

**Comment by tadatuta** [comment]
I think `this.naming` whould be fine

**Comment by miripiruni** [comment]
@tadatuta What kind of methods needed? `ClassBuilder` API maybe replaced or modified in future. Is it OK to make visible all of it's methods right now?

**Comment by tadatuta** [comment]
@miripiruni you are right. I think possibility to get delimiters and stringify an entity with current notation should be enough.

**Comment by miripiruni** [comment]
“[I decided to close it as long as we do not understand, for whom it is actually needed.](https://github.com/bem/bem-xjst/pull/163#issuecomment-172847195)”
