### ISSUE TITLE
Minor bem-xjst release

### ISSUE THREAD

**Issue by arikon** [bem/bem-xjst#153]
Following commits are backward compatible and may be released as `4.3.0`: https://github.com/bem/bem-xjst/compare/v4.2.7...04ec2b0f

**Comment by blond** [comment]
@arikon you mean major?

**Comment by tadatuta** [comment]
@blond not yet, we decided to release backward compatible changes first.

**Comment by tadatuta** [comment]
@miripiruni I updated the range in description but just found out we don't have permission to release version to npm.

@indutny Please give permissions for the package to @arikon @miripiruni and @tadatuta, we won't make any harm ;)

**Comment by miripiruni** [comment]
- [x] [npm](https://www.npmjs.com/package/bem-xjst)
 - [x] [diff v4.2.7...v4.3.0](https://github.com/bem/bem-xjst/compare/v4.2.7...v4.3.0)
 - [x] [online](http://bem.github.io/bem-xjst/)

**Comment by arikon** [comment]
:+1:

**Comment by blond** [comment]
Why don't you write the changelog?

**Comment by miripiruni** [comment]
@blond I collect issues in [milestones](https://github.com/bem/bem-xjst/milestones).
