### ISSUE TITLE
Document all the differences from bem-xjst@1.x

### ISSUE THREAD

**Issue by arikon** [bem/bem-xjst#154]

**Comment by tadatuta** [comment]
Current docs are in https://github.com/bem/bem-core/tree/v2/common.docs and are rendered on bem.info: https://ru.bem.info/technology/bemhtml/v2/intro/ but as base templates are now in `bem-xjst` itself we should move docs to this package.

Still the most urgent is migration guide which is kinda described [here](https://nda.ya.ru/3RCohw).

**Comment by miripiruni** [comment]
I think it’s done. See [Notable changes between bem-xjst@1.x and 2.x](https://github.com/bem/bem-xjst/wiki/Notable-changes-between-bem-xjst@1.x-and-bem-xjst@2.x).

May I close this issue?

**Comment by tadatuta** [comment]
@miripiruni I think differences in "user experience" should also be described (no more compilation results in much faster build time, possibility to add templates in runtime, execution performance increased, etc) and node.js API changes as well.

But the very first thing is to describe a way to convert old templates to JS syntax.

**Comment by miripiruni** [comment]
@tadatuta Done!

**Comment by miripiruni** [comment]
@tadatuta May I close?
