### ISSUE TITLE
BEMTREE: Implement async support

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#155]

**Comment by zxqfox** [comment]
We decided to NOT support async BEMTREE, isn't it?

**Comment by zakaratcha** [comment]
And what for it's needed now without async?

**Comment by tadatuta** [comment]
@zakaratcha exactly for the same as before ;)
Collect all needed data beforehand and use BEMTREE to map raw data to BEMJSON.

**Comment by zakaratcha** [comment]
Is there possibility that async will be returned to BEMTREE in future?
And what version of bem-core is lastest with async BEMTREE?

**Comment by miripiruni** [comment]
We decided to do not support this feature.
