### ISSUE TITLE
Move docs from bem-core to bem-xjst

### ISSUE THREAD

**Issue by arikon** [bem/bem-xjst#166]
https://github.com/bem/bem-core/tree/v2/common.docs

**Comment by miripiruni** [comment]
@tadatuta can we close it because we already have documentation?

**Comment by tadatuta** [comment]
Well, this issue can be closed but we should remember that there's also English translation of old docs on bem.info.

**Comment by miripiruni** [comment]
I think we need to invite professional translator (namely not me :) to this task.

**Comment by zxqfox** [comment]
> we should remember that there's also English translation of old docs on bem.info.

We need another issue for that?
