### ISSUE TITLE
ES6-sugar for templates

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#171]
Is it possible to pass node and/or ctx as parameters to matcher/template to use arrow functions in templates:
```js
block('*').match(node => node.url).tag()('a');
block('*').cls()(node => `position${node.position}`);
block('*').content()({ctx} => [ctx.text, applyNext()]);
```

**Comment by voischev** [comment]
:fire:

**Comment by narqo** [comment]
It didn't work last time #13 :(

**Comment by indutny** [comment]
Let's do it this time! :)

**Comment by zxqfox** [comment]
My argues:
1. We all love sugar.
2. BEMHTML uses the result of matcher/template function and arrow function returns the value by default.
3. idk, @indutny already agreed ;-D
