### ISSUE TITLE
.bydefault()/.force() helper suggestions

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#175]
We have different merging with bemjson behaviour for `content`, `tag`, `cls` and `attrs` modes.

`content` mode executes in anyway.
`tag` mode won't be executed if bemjson had `tag` property.
`attrs` & `cls` from template will be merged with `attrs` property in result.

All of this forces users to use `.def` mode while using it much can significantly decrease performance.

I guess we should make as many helpers as we can to reduce `.def` usage at all.

The bright example is `.bydefault` helper that can hold the value for this mode by default (if property doesn't exist in users data).

Template can look like:
```js
block('input').bydefault()(
  tag()('input'),
  attrs()({placeholder: 'Enter a value'})
  // etc.
);
```

And then we can redefine this easily with our current templates as well.

Also there are example with inconsistency between tag, content and attrs: [sandbox example](http://bem.github.io/bem-xjst/?bemhtml=block(%27*%27)(%0A%20%20%20%20content()(%27x%27%2C%20%27y%27)%2C%0A%20%20%20%20tag()(%27x%27%2C%20%27y%27)%2C%0A%20%20%20%20attrs()(%7Bx%3A%20%27y%27%7D%2C%20%7Bz%3A%20%27≈%27%7D)%0A%20%20%20%20%2C%20cls()(%27lol%27)%0A)%3B%0A&bemjson=(%7B%0A%20%20%20%20block%3A%20%27yomama%27%2C%0A%20%20%20%20mods%3A%20%7Bm%3A%20%27v%27%7D%2C%0A%20%20%20%20content%3A%20%27bemjson%27%2C%0A%20%20%20%20tag%3A%20%27xxx%27%2C%0A%20%20%20%20attrs%3A%20%7Bbem%3A%20%27json%27%7D%2C%0A%20%20%20%20cls%3A%20%27opa%27%0A%7D)%3B%0A)

/cc @veged @indutny

**Comment by veged** [comment]
I think we need just clarify difference for redefining between all modes and keep BEMXJST terms domain as thin as possible.

**Comment by zxqfox** [comment]
@veged Did you even read description? ;-)

**Comment by veged** [comment]
@zxqfox formally yes — I try my best ;-)

read twice and still remain in conviction with my comment

so let's discuss it on nearest meeting
