### ISSUE TITLE
BEMHTML renderMix: skip mix item if falsy

### ISSUE THREAD

**Issue by baymer** [bem/bem-xjst#179]
I think, it should check is the `item` truthy: `if (item)...`
https://github.com/bem/bem-xjst/blob/8b650e78f211f3e5ca1c7897f325a7d8830779ab/lib/bemhtml/index.js#L208

**Comment by miripiruni** [comment]
@baymer can you share test case?

**Comment by alsun** [comment]
`mix: [ { block: 'story' }, ctx.title ? { block: 'title' } : null  ]`

**Comment by miripiruni** [comment]
@baymer [v4.3.3](https://github.com/bem/bem-xjst/blob/master/CHANGELOG.md#2016-01-22-v433-miripiruni)
