### ISSUE TITLE
extend() is broken

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#180]
First part of the issue is about bug:
Now `extend()` mode results in infinite loop (it returns `applyCtx()` of the same `ctx` so same `extend()` template matches it again).

Tests are passed accidentally because `ctx` is changed there.

Second part is a suggestion to change semantic of `extend()` to extend not `this.ctx` but `this` and the same syntax with dot notation should be supported as in `applyNext()`: `block('b1').extend({ 'ctx.blah': 'ololo' })`.

**Comment by tadatuta** [comment]
cc @veged

**Comment by zxqfox** [comment]
You proposing to extend context so why just not to use `.extend()` for that?

**Comment by tadatuta** [comment]
@zxqfox You are right but it's not working as I expected for some reason :(

```js
var BEMHTML = require('./bundle.bemhtml.js');

BEMHTML.compile(function() {
    block('b1')(
        extend()({ a: 'blah' }),
        elem('e1').content()(function() { return this.a; })
    );
});

var html = BEMHTML.apply({ block: 'b1', content: { elem: 'e1' } });

console.log(html);
```
results in infinite loop.

**Comment by tadatuta** [comment]
seems like `extend()` works just for `elem` field and it extends `this.ctx` not `this`, isn't it?

**Comment by zxqfox** [comment]
@tadatuta I'm wondered that it's working somehow at all. Shouldn't this be fixed?

**Comment by tadatuta** [comment]
@zxqfox  sure. funny thing — there are tests for it and they pass :)

**Comment by tadatuta** [comment]
just totally rewritten issue title and description

**Comment by veged** [comment]
@tadatuta Am I right that you suggest `block('b1').extend({ 'ctx.blah': 'ololo' })` as shortcut for `block('b1').def(function() { return applyNext({ 'ctx.blah': 'ololo' }) })`?

**Comment by tadatuta** [comment]
@veged yes

**Comment by veged** [comment]
@tadatuta Ok, but we need to double think about naming... I'm strongly against redefining of current `extend`.

Could you provide more examples of such cases, maybe it bring inspiration.

**Comment by tadatuta** [comment]
@veged 
Won't it be more consistent to have `extend()` and (optionally) `extendCtx()` as we have `applyNext()` and `applyCtx()`?

There shouldn't be any issues with changing `extend()` semantics as it turned out not to work at all now.
We need shortcut to extend `this` as it's common way to tunnel some data to child nodes. And changes for `this.ctx` is just a subset of it, isn't it?

**Comment by veged** [comment]
@tadatuta ok

**Comment by tadatuta** [comment]
It turned out there's more then none users of this mode (YaMoney ;)

Let's fix it!

**Comment by miripiruni** [comment]
@tadatuta can you show their use case?

**Comment by tadatuta** [comment]
just sent you an email

**Comment by tadatuta** [comment]
it turned out it was other `extend` :)

**Comment by miripiruni** [comment]
v8.3.1
