### ISSUE TITLE
[Online demo] Shortcut url

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#186]
Give ability to share http://clck.ru/Sseb90sb instead of  http://bem.github.io/bem-xjst/?bemhtml=block(%27b%27)(%0A%20%20%20%20content()(function()%7B%0A%20%20%20%20%20%20%20%20return%20apply(%27counter%27%2C%20%7B%20elem%3A%20%27swag%27%2C%20cid%3A%201234%20%7D)%3B%0A%20%20%20%20%7D)%2C%0A%20%20%20%20%0A%20%20%20%20%2F*elem(%27swag%27).*%2Fmode(%27counter%27)(function()%20%7B%0A%20%20%20%20%20%20%20%20return%20this.cid%3B%0A%20%20%20%20%7D)%0A)%3B&bemjson=(%7B%20block%3A%20%27b%27%20%7D)%3B%0A

**Comment by voischev** [comment]
:+1:

**Comment by miripiruni** [comment]
Already done.
