### ISSUE TITLE
BEMHTML: should merge class from attrs and bem class

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#188]
```js
  it('should merge class from attrs and bem class', function() {
    test(function() {
      block('b').attrs()(function() {
        return { class: 'test' };
      });
    }, { block: 'b' }, '<div class="b test"></div>');
  });
```

actual result in 5.0.0: `<div class="b" class="test"></div>`

**Comment by mishanga** [comment]
В BH сейчас так не работает, он тоже дает на выходе два атрибута class. И тестов таких нет.
Думаю, надо запретить явно модифицировать атрибут class.

**Comment by voischev** [comment]
Как это запретить? `class` вдруг стал не `attrs`?

**Comment by mishanga** [comment]
Да, class — это не attrs :) Точно так же, как data-bem:
JSON: `{ block: 'a', js: true }`
XJST: `block('a').attrs()({ 'data-bem': 'lol' })`
HTML: `<div class="a i-bem" data-bem='{"a":{}}' data-bem="lol"></div>`

**Comment by voischev** [comment]
Никто в здравом уме не будет писать data-bem в attrs ... а вот class может захотеть написать любой новичек. Попробуй из запретить писать в attrs 

а что нельзя сделать что бы все что в attrs перетерало то что из мод приехало? Это более ожидаемое поведение. 
Запретить? Может предупредить?

**Comment by zxqfox** [comment]
Более ожидаемое, чем вывод обоих? оба варианта сомнительные.

А вот в режиме отладки хорошо бы ругаться на `{attrs: { class: 'qwe' }}`, равно как и на `data-bem` там же.

**Comment by voischev** [comment]
Вывод обоих это кстати похоже на "предупредить". Ничего против не имею

**Comment by mishanga** [comment]
@miripiruni предлагаю закрыть по won't fix и считать нынешнее поведение правильным.

**Comment by miripiruni** [comment]
Closed in favor https://github.com/bem/bem-xjst/issues/212
