### ISSUE TITLE
CLI: implement apply templates to bemjson

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#191]
```bash
./bin/bem-xsjt --templates=my-templates.js --data=my-bemjson.js --output=result.html
```

or
```bash
./bin/bem-xsjt -t my-templates.js -d my-bemjson.js -o result.html
```

Breaking changes that I would like to see here: in current version stdout will give you a bundle of bemhtml or bemtree engine + user templates. I’d like to place this behaviour under flag `--bundle`.

**Comment by tadatuta** [comment]
it won't be consistent for BEMTREE

**Comment by zxqfox** [comment]
For BEMTREE it could output bemjson, right?

**Comment by miripiruni** [comment]
Not actual.

**Comment by tadatuta** [comment]
> Not actual

but why?

**Comment by miripiruni** [comment]
@tadatuta it seems that only I think about it.
