### ISSUE TITLE
Make this.extend as close as possible to Object.assign

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#199]
It's a breaking thing, but annoying.

**Comment by Yeti-or** [comment]
how about polyfill?

**Comment by miripiruni** [comment]
@zxqfox why `bem-xjst` should have this ternary inspection? 

If you can use `Object.assign` in templates it’s good. But why we need a polyfill in `this.extend`?

**Comment by zxqfox** [comment]
You suggest to drop this.extend?

**Comment by miripiruni** [comment]
Yep. Someday.

**Comment by miripiruni** [comment]
@zxqfox I can close issue in the hope that someday we will declare `this.extend` deprecated?

**Comment by voischev** [comment]
Ох... Вот это будет больно.

**Comment by zxqfox** [comment]
@miripiruni I don't see why we can't improve `this.extend` for now. Regardless of the deprecation. ;-)

**Comment by miripiruni** [comment]
@zxqfox what benefits?

**Comment by zxqfox** [comment]
Expectations: https://lodash.com/docs#assignIn http://api.jquery.com/jQuery.extend/
Reality: Well, you know.

**Comment by miripiruni** [comment]
So can I close?

**Comment by narqo** [comment]
:+1: for deprecation of `this.extend()`.

> Expectations: https://lodash.com/docs#assignIn http://api.jquery.com/jQuery.extend/

`Object.assign()` and `$.extend()` work different (at least for keys \w `undefined` values), so the point about expectations is quite doubtful, IMHO.

**Comment by zxqfox** [comment]
@narqo Yes, but the current behaviour is quitely different from both of them. It's even worse.

**Comment by miripiruni** [comment]
1. Someday we mark `this.extend` as deprecated.
2. You can start using `Object.assign` today.
