### ISSUE TITLE
applyCtx brokes context if there are star matchers only

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#203]
Example: http://goo.gl/LpdqpQ

**Comment by miripiruni** [comment]
Hardcode :)

**Comment by miripiruni** [comment]
@zxqfox эм, чот я подзабыл, в чем именно баг-то?

**Comment by zxqfox** [comment]
В том, что у тебя есть 3 блока на входе, а на выходе шаблон применяется только к одному, потому что this не очищается.
Может быть это даже мы специально не хотели чинить, потому что это типа медленно. Но сейчас мы же можем как-то проверить насколько оно проседает?
Может быть MutationObserver повесить на this? Или хотя бы в дебаг режиме ругаться на такое, а само поведение оставить как есть?

**Comment by miripiruni** [comment]
> В том, что у тебя есть 3 блока на входе, а на выходе шаблон применяется только к одному, потому что this не очищается.

А, собственно, на основании чего контекст должен очищаться?

1. Шаблон по звездочке  матчится на первый блок 'a'
2. выставляется this._qweqweqwe.
3. Вызывается applyCtx({ … })
4. Вызывается дефолтный def(), так как есть `return applyNext();` Шаблонизируется первый блок 'a' как обычно.
5. Второй и третий блок 'a' не матчатся так как есть проверка на falsy this._qweqweqwe.

**Comment by zxqfox** [comment]
По определению, Слав) а логика, которую ты расписал, еще имеет шаг почистить контекст для поддерева

**Comment by zxqfox** [comment]
@miripiruni Когда я создавал задачу, кстати, мне казалось, что это надо чинить, но кажется, что не обязательно.

Я точно помню, что мы это не раз обсуждали, поднимал вопрос @tadatuta, несколько раз кажется для bemtree, но в итоге остановились на том, что это бьёт в производительность.

Еще кажется, что достаточно будет какого-то режима для отладки. Или даже не нужен он, тогда можно закрыть

**Comment by miripiruni** [comment]
@zxqfox см https://github.com/bem/bem-xjst/pull/436/commits/80ff3c1913a535f5e1bbe6fca0248649d8d9e025
