### ISSUE TITLE
New mode `mods` for bemhtml

### ISSUE THREAD

**Issue by a-x-** [bem/bem-xjst#209]
Let's use `mods()({ ... my mods ... })` expr in BEMHTML.js instead of
```js
def()(function(){
    this.ctx.mods = this.extend(this.ctx.mods || {}, { ... my mods ... });
    return applyNext();
})
```

i try implement mods myself, but got defeat

----
I tried make PR in bem-core recently, but its't correct place
https://github.com/bem/bem-core/pull/1264
```js
BEMContext.prototype.mods = function(mods) {
    this.ctx.mods = this.extend(this.ctx.mods || {}, mods);
    return applyNext();
};
```

**Comment by a-x-** [comment]
Кажется что mods(), так же важна как и mix() и пр.

**Comment by miripiruni** [comment]
Closed as duplicate https://github.com/bem/bem-xjst/issues/107
