### ISSUE TITLE
Global block ctx

### ISSUE THREAD

**Issue by a-x-** [bem/bem-xjst#210]
now i need proxy ctx in elems
stupid example:
```js
block('block')(
  content()([ { elem: 'elem1', foo1: this.ctx.foo1, foo2: this.ctx.foo2 }, { elem: 'elem2', foo2: this.ctx.foo2, foo3: this.ctx.foo3 } ]),
  elem('elem1').content(function(){return this.ctx.foo1 * this.ctx.foo2})
  elem('elem2').content(function(){return this.ctx.foo2 * this.ctx.foo3})
)
```

In ideal world:
```js
block('block')(
  content()([ { elem: 'elem1' }, { elem: 'elem2' } ]),
  elem('elem1').content(function(){return this.blockCtx.foo1 * this.blockCtx.foo2})
  elem('elem2').content(function(){return this.blockCtx.foo2 * this.blockCtx.foo3})
)
```

----

p.s. i understand, that global vars are evil, buuut...

**Comment by miripiruni** [comment]
You may be surprised, but [here is live example of what you want](http://bem.github.io/bem-xjst/?bemhtml=block(%27b%27)(%0A%20%20%20%20content()(function()%20%7B%0A%20%20%20%20%20%20%20%20var%20ctx%20%3D%20this.ctx%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20return%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20elem%3A%20%27elem1%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20ctx.foo1%20*%20ctx.foo2%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20elem%3A%20%27elem2%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20content%3A%20ctx.foo2%20*%20ctx.foo3%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%5D%3B%0A%20%20%20%20%7D)%0A)%3B&bemjson=(%7B%0A%20%20%20%20block%3A%20%27b%27%2C%0A%20%20%20%20foo1%3A%201%2C%0A%20%20%20%20foo2%3A%202%2C%0A%20%20%20%20foo3%3A%203%0A%7D)%3B).

**Comment by a-x-** [comment]
no, it's not

**Comment by a-x-** [comment]
i have to proxy all params into elems now

i want access all block's params in its elems via API, w/o proxing

**Comment by a-x-** [comment]
Это частый кейс, и проксирование обычно тривиально и только засоряет шаблоны

**Comment by miripiruni** [comment]
Can you show more examples?

**Comment by miripiruni** [comment]
@a-x- thank you for your feedback!

**Comment by a-x-** [comment]
here: https://gist.github.com/a-x-/a380c1f4d5d0dc997e7a
we set global ctx (`this.params = this.ctx.params`) and we use it around wide block elems
