### ISSUE TITLE
Change api: this.param instead of this.ctx.param

### ISSUE THREAD

**Issue by a-x-** [bem/bem-xjst#211]
there is crazy non-realistic idea...

move service stuff in something like `this._`, because its are used rarely.
and move block's `params` from `this.ctx` to `this`, because its are used frequently

**Comment by miripiruni** [comment]
@a-x- what kind of stuff you named “service stuff”?

Are you read [documentation](https://github.com/bem/bem-xjst/blob/master/docs/ru/6-templates-context.md#Что-доступно-в-теле-шаблона)? In this section explained in detail about semantics of `this` fields and `this.ctx`.

Feel free to reopen this discussion if something not clear.

**Comment by a-x-** [comment]
Thank you,
I haven't seen above linked documentation page

Recently i dramatically improve my xjst understanding,
and i know about this.ctx.mods and this.mods, for example today.

I'll read doc too.

**Comment by a-x-** [comment]
any way, `this.ctx.someParam`, is uses more frequently than `this.something` as i see

**Comment by a-x-** [comment]
for example in our project:
```bash
ALL_THIS=$(ag -Gbemhtml 'this\.' | wc -l);
THIS_CTX=$(ag -Gbemhtml 'this\.ctx' | wc -l);
node -p "(($ALL_THIS - $THIS_CTX) / $ALL_THIS * 100).toFixed(2) + '%'"
```
> 9.31%

**Comment by miripiruni** [comment]
What do not you like? That `this.ctx.prop` is longer than `this.prop`? We can’t merge this.ctx fields and this fields because it’s different objects.

**Comment by miripiruni** [comment]
@a-x- we can’t change API as you suggest in issue title. Because of bemjson:
```js
{
    block: 'example',
    ctx: { something: 'wrong' },
    reapply: 'oh, my',
    isSimple: 'etc'
}
```

```js
block('example').def()(function() {
    var html = this.reapply({ block: 'reapply-me' });
    …
    return this.isSimple('test');
})
```

But I have good news for you: take a look at https://github.com/bem/bem-xjst/pull/200

After merge you can write templates:
```js
// BEMJSON: { block: 'b', prop: 'bar' }
// Template: 
block('b').def()(function(_, ctx) {
    return ctx.prop; // 'bar'
});
```

**Comment by a-x-** [comment]
cool
