### ISSUE TITLE
Mods with numeric values does not match to string matchers

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#220]
`mod('a', 1) does not match { mods: { a: '1' } }`.

As well as opposite:
`mod('a', '1') does not match { mods: { a: 1 } }`.

http://goo.gl/y1BOEY

Same with boolean modifiers with falsy values `''` and `false`.

**Comment by miripiruni** [comment]
We need to disscuss current behaviour of `mod()` mode 
Here is [showcase](http://goo.gl/vDHtyW).

**Comment by miripiruni** [comment]
We definitely should write about it in docs.

**Comment by zxqfox** [comment]
What's changed?

**Comment by miripiruni** [comment]
@zxqfox look at my [showcase](http://goo.gl/jho9eV).

**Comment by zxqfox** [comment]
We decided it's a bug the last time. What's changed?
