### ISSUE TITLE
separate engines as npm packages

### ISSUE THREAD

**Issue by awinogradov** [bem/bem-xjst#224]
Ok, guys!;) 

Fast explanation:

``` bash
npm i xjst xjst-bemhtml xjst-bemtree xjst-virtual xjst-svg 
```

**Comment by blond** [comment]
Why? :)

**Comment by awinogradov** [comment]
@blond because I want to use different engines in different projects. I want to write other engines for bem-xjst. Now new engines from community can't be in bem-xjst and I don't way to make useful extensions. Every engine can work without other engines. Why I should install all with bem-xjst?

**Comment by tadatuta** [comment]
@awinogradov 
actually there's no harm in having some extra engines in your `node_modules` folder, you won't get useless code in built bundle anyway.

**Comment by awinogradov** [comment]
yes) I can generate every bungle in different npm packages. You know it;)

**Comment by Guria** [comment]
+1
Though it will require some better splitting of responsibility and some breaking changes.
Eg:
```js
var BEMHTML = require('xjst')('bemhtml') // will require runtime from `xjst-bemhtml` package
```

**Comment by miripiruni** [comment]
We will not do it. BEMTREE + BEMHTML = default features (engines) of bem-xjst because of customers specialty. Other engines may use bem-xjst as dependency. 

Maybe someday it will change. But not today or tomorrow.
