### ISSUE TITLE
BEMTREE demo

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#230]
bem-xjst have BEMTREE engine and BEMHTML engine. In online demo we need to have an selector for engines.

Online demo: https://bem.github.io/bem-xjst

Source code of online demo: https://github.com/bem/bem-xjst/tree/gh-pages

**Comment by miripiruni** [comment]
// cc  @tenorok

**Comment by tenorok** [comment]
Thank you for this issue.
May be it would be more understandably for users who want learn bem-xjst through practicle examples.

**Comment by miripiruni** [comment]
See https://github.com/bem/bem-xjst/pull/238/commits/3260190d3654730eda0cbe0d6ac02c9107f0e663

**Comment by tadatuta** [comment]
any progress here?

**Comment by miripiruni** [comment]
Not yet. I’ll try to make this today.

**Comment by miripiruni** [comment]
Fixed. Thanks @mikhailrojo
