### ISSUE TITLE
`BEM.I18N` stub for demo

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#231]
We need to mock this function in online demo: https://github.com/bem/bem-core/blob/v3/common.blocks/i18n/i18n.test.js

`BEM.I18N()` should exist in global scope for conveniences. Just in case I want copy-paste example from real project:

``` js
block('search-item').content()(function() {
    return BEM.I18N('search-page', 'search-item');
})
```

`BEM.I18N('search-page', 'search-item')` should return `search-item`.

Online demo: https://bem.github.io/bem-xjst

Source code of online demo: https://github.com/bem/bem-xjst/tree/gh-pages

**Comment by zxqfox** [comment]
In bem-xjst?!

**Comment by miripiruni** [comment]
In online demo. Just simple stub like this: `function (str) { return str; }`

**Comment by mikhailrojo** [comment]
то есть подразумевается добавление вот этого пакета в общую сборку? 
https://github.com/enb/enb-bem-i18n

**Comment by miripiruni** [comment]
Нет. Как я уже писал тебе в Telegram:

<img width="449" alt="screen shot 2016-12-15 at 14 04 51" src="https://cloud.githubusercontent.com/assets/144537/21221702/7f2e7dd2-c2cf-11e6-88dc-3dfdfafb1636.png">


Цель, которую хочется достичь этой задачей весьма невеликая — уметь исполнять в песочнице код, который скопипастили из реального проекта, где есть I18N.

Нужно просто научить демо исполнять что-то такое:

```
block('b').content()(function() { return this.i18n('block', 'key'); });

block('b').content()(function() { return BEM.I18N('block', 'key'); });
```

**Comment by miripiruni** [comment]
Fixed by @mikhailrojo
