### ISSUE TITLE
What about alert access incorrect sub-predicate

### ISSUE THREAD

**Issue by a-x-** [bem/bem-xjst#244]
Following error:
`block('commercial-controller').js(true);`
results piece of awesome in ever irrelevant block and no any debug info
![2016-04-14_02-01-26](https://cloud.githubusercontent.com/assets/6201068/14512150/93c9d118-01ed-11e6-9981-ac82513cacdd.png)

p.s. normal look:
![2016-04-14_02-05-56](https://cloud.githubusercontent.com/assets/6201068/14512182/ded2e492-01ed-11e6-8f9a-1b6e6def2f94.png)

**Comment by zxqfox** [comment]
Did you tried: `.js()(true);`?

**Comment by a-x-** [comment]
Is it possible alert (throw/console.log/...) these cases?

**Comment by zxqfox** [comment]
Did you tried to update?

**Comment by a-x-** [comment]
yeah, i know about my error

**Comment by a-x-** [comment]
it is another question

meta question)

**Comment by a-x-** [comment]
i want bem-xjst to make local warns for cases like mine

**Comment by zxqfox** [comment]
I'm just sure that it's already throwing ;-) https://github.com/bem/bem-xjst/blob/master/test/modes-js-test.js#L7

**Comment by a-x-** [comment]
yep, i know :)
but this warn suppressed in most cases.

may be add throw?

**Comment by a-x-** [comment]
may be there is catch in our templates... :hankey:

**Comment by zxqfox** [comment]
You should try enb-debug and all this shit... https://nda.ya.ru/3RUJzm

**Comment by a-x-** [comment]
thanks!
