### ISSUE TITLE
Helper to reverse sub-predicate's condition

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#246]
Related #175, #245, #336

Something like `.not()` for:
```js
block('b42').match(function() { return this.mods.holy !== 'moly'; })...
// →
block('b42').not(mod('holy', 'moly'))...
```

**Comment by miripiruni** [comment]
there is a problem with `elem()` subpredicate and automatically insertion of `!this.elem`: `block('b1').not(elem('e1'))` will be treated as `block('b1').match(function() {return !this.elem}).match(function() { return this.elem !== 'e1' })`

**Comment by miripiruni** [comment]
it's better to introduce separate `notMod`, `notElemMod`, `notBlock`, `notElem`

**Comment by miripiruni** [comment]
to continue with this issue we need strong proof about current codebase of wide usage for such cases

**Comment by baymer** [comment]
When we need to check is mod not exist we can not use pattern like that:
```
block('doc').match(function() {return !this.mods.position})
```
Because `position` can be zero or some thing like that.
So we need use
```
block('doc').match(function() {return typeof this.mods.position === 'undefined'}) ||
block('doc').match(function() {return !this.mods.hasOwnProperty('position')}) ||
block('doc').match(function() {return !('position' in this.mods)})
```
But, much better
```
block('doc').not(mod('position')) // like css: .doc:not(div)
```

**Comment by miripiruni** [comment]
For me `.not()` is bad idea because as soon we introduce `not` someone would combine it with all subpredicates witch is not working:

```js
block('a').not(
  tag()('a'),
  attrs()({ test: '1' })
);
``` 

Again, I would like to see codebase for proof it’s real needed.
