### ISSUE TITLE
Semantic: change behaviour of `mix`, `js` and `attrs` modes

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#261]
`.mix()('b')` should set `b` as mix. Last call of `mix()` set new value which is not extended previous.
`.addMix()('newMix')` should extend value of previous mix value.

The same for `js()` and `attrs()`.

Also, I think we need `addContent()` mode to avoid `applyNext()` copypaste in chain of the same mode templates.

BTW, see https://gist.github.com/miripiruni/7561cc8ad56d0d4d5184

**Comment by tadatuta** [comment]
Please refer to old issues https://github.com/bem/bem-xjst/issues/242 (based on https://github.com/bem/bem-core/issues/820)

**Comment by tadatuta** [comment]
Discussed there's an issue with possibility to dismiss `addMix()` declared on previous level.

**Comment by zxqfox** [comment]
> I think we need addContent() mode to avoid applyNext()
I don't see what we get with avoiding applyNext() calls. `addContent`, `addMix`, `addAnythingElse` won't make API easier.
Compare:
```js
block('a').addMix()(() => {elem: 'e'});
// vs
block('a').mix()(() => applyNext().concat({elem: 'e'}));

// and
block('a').addContent()('qwe');
// vs
block('a').content()(() => applyNext().concat('qwe'));
```
Worth?

**Comment by miripiruni** [comment]
@zxqfox Incorrect example. Look: `block('a').mix()(() => applyNext().concat({elem: 'e'}));` will fall if `applyNext()` return not an Array. First of all you need to check type.

With `addMix`/`addAttrs`/etc we’ll get **expressiveness** and **brevity**. The correct compare:

```js
block('page').addMix()(() => {block: 'mixed'});
// vs
block('page').mix()(function() {
    var mixes = applyNext();
    if (!Array.isArray(mixes)) mixes = [ mixes ];
    return mixes.concat('mixed');
});
```

**Comment by zxqfox** [comment]
Ok, but let's do `mix` an array. It's much easier and cleaner, isn't it?

**Comment by miripiruni** [comment]
@zxqfox OK, but **where** you would like to change it?

**Comment by miripiruni** [comment]
@zxqfox я процитирую себя самого:

> если мы хотим сформировать выход (часть выходного дерева) то нужно использовать режимы. То есть вся «запись» должна происходить в них. А чтение, с целью проверить что-либо, нужно производить в нормализованных значениях.

[proof](https://bem-team.slack.com/?redir=%2Farchives%2Fbem-xjst%2Fp1471245364000135)

**Comment by zxqfox** [comment]
Ну так давай нормализовывать this.mix, равно как мы это делаем с this.mods? Аналогично this.js, this.attrs

**Comment by miripiruni** [comment]
@zxqfox the only reason why we change `this.mods`/`this.elemMods` now is that we don’t have any other way to do it in current version. We need change it. We need more explicit way to make output.

Compare:
```js
block('a').def()(function() {
    this.mix.push('mixed');
    return applyNext();
});
// vs
block('a').addMix()('mixed'); // Much more explicitly than def() with side effect.
```

**Comment by zxqfox** [comment]
Т.е. в будущем мы не будем нормализовывать mods, elemMods?
Я не понял аргументации ПРОТИВ нормализации mix, js, attrs.

**Comment by miripiruni** [comment]
@zxqfox я против записи в `this.*`, но не против нормализации.

**Comment by zxqfox** [comment]
@miripiruni Я против записи в ctx ;-)

**Comment by miripiruni** [comment]
https://github.com/bem/bem-xjst/releases/tag/v8.0.0
