### ISSUE TITLE
Is it possible to build it with webpack?

### ISSUE THREAD

**Issue by vladkhvo** [bem/bem-xjst#271]
I couldn't build it with webpack, because node-module fs broke build.

```
$ webpack index.js bundl.js
ERROR in ./~/bem-xjst/index.js
Module not found: Error: Cannot resolve module 'fs' in C:\Users\khvostov\test\cc-exp\node_modules\bem-xjst
 @ ./~/bem-xjst/index.js 1:9-22

```

Is it possible to use it on client-side, without enb?

**Comment by zxqfox** [comment]
[`require('bem-xjst').generate("block('a').tag()('a');")`](https://github.com/bem/bem-xjst/#generatestring-or-function) will make a ready for use bundle for you.
 
Look also at https://github.com/gulp-bem/gulp-bem-xjst — "without enb" (as requested).

**Comment by vladkhvo** [comment]
Thanks for answer!

**Comment by zxqfox** [comment]
Btw, take a look at https://github.com/bempack/bemhtml-loader /cc @sullenor
