### ISSUE TITLE
Support `mod('m')` and `elemMod('em')` without second argument.

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#274]
From [i-bem documentation](https://en.bem.info/technology/i-bem/v2/i-bem-js-mods/#modifiers):

> A simple modifier is a special case when only the presence or absence of the modifier on the block is important, and its value is insignificant. An example is the modifier describing the ”disabled“ state: disabled. A modifier with an unspecified i-bem.js value is interpreted as boolean and automatically assigned the value true.

`mod('m')` is the same as `mod('m', true)`

**Comment by zxqfox** [comment]
> mod('m') is the same as mod('m', true)

Are you sure?

**Comment by miripiruni** [comment]
> A modifier with an unspecified i-bem.js value is interpreted as boolean and automatically assigned the value true.

**Comment by veged** [comment]
no! you refer to `setMod('m1')`, which is exactly shortcut for `setMod('m1', true)`, BUT `mod('m1')` in terms of "matching" is the same as `mod('m1', '*')`

it's not clear from [documentation](https://en.bem.info/technology/i-bem/v2/i-bem-js-decl/#adding-a-modifier-to-a-block) (sorry, that's my fault)

**Comment by miripiruni** [comment]
Oh my…

**Comment by zxqfox** [comment]
Insane! <3 u all, ty for clarification!

**Comment by miripiruni** [comment]
https://github.com/bem/bem-xjst/releases/tag/v7.3.0
