### ISSUE TITLE
improve `def` mode description

### ISSUE THREAD

**Issue by Guria** [bem/bem-xjst#276]
Documentation warns us not to use `def` without truly necessity:
> This is a special mode that shouldn’t be used unless truly necessary.

But at the same time this mode is actively used in `bem-components`.

We need better examples how and when this mode should be used.

**Comment by tadatuta** [comment]
We need to fix `extend()` mode (see [#180](https://github.com/bem/bem-xjst/issues/180)) and implement `mods()` ([#107](https://github.com/bem/bem-xjst/issues/107)).

It will give possibility to remove most of `def()` in `bem-components`.

**Comment by miripiruni** [comment]
@Guria may I close this issue?

**Comment by Guria** [comment]
Feel free to decide. It's ok to close for me if after mentioned issues resolved wouldn't be much actual `def`mode use cases.
