### ISSUE TITLE
bemhtml specific in bemxjst runtime

### ISSUE THREAD

**Issue by Guria** [bem/bem-xjst#286]
`bemxjst` has some specifics not needed for `bemtree` runtime, like:
https://github.com/bem/bem-xjst/blob/v6.5.1/lib/bemxjst/tree.js#L354-L376
Not so much, but I wonder if it's possible to have better split of responsibilities.

**Comment by miripiruni** [comment]
I think we need to move these lines to `lib/bemhtml/tree.js`.

**Comment by miripiruni** [comment]
PR’s are welcome ;)

**Comment by miripiruni** [comment]
Since we want to reduce bundle size and https://github.com/bem/bem-xjst/pull/382 it’s not actual any more.
