### ISSUE TITLE
test is controversial

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-xjst#291]
https://github.com/bem/bem-xjst/blob/a67900859a928aae53a869cbebca72ba3177b5a3/test/runtime-escaping-test.js#L42
test description and it's content are contradictory

**Comment by miripiruni** [comment]
@Yeti-or you right, I’ll rewrite test description.

**Comment by Yeti-or** [comment]
maybe we need two test case here:
1. ` { block: 'b', html: '<unescaped>', content: 'safe text' }`
2. ` { html: '<unescaped>', content: 'safe text' }`
