### ISSUE TITLE
Calling incomplete predicates acts as def mode

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#297]
I'm not sure it's wrong but probably we should document and test it. Or just decide how it should works

```js
block('a')(function(){
    return applyNext({ctx: {tag: 'b'}});
});
```

http://goo.gl/CL9PSF

**Comment by miripiruni** [comment]
It’s not bug, in [documentation](https://github.com/bem/bem-xjst/blob/master/docs/en/7-runtime.md#applynext) we show that `applyNext` have argument for change context.

**Comment by zxqfox** [comment]
It's not about passing params to applyNext

**Comment by miripiruni** [comment]
`incomplete predicates acts as def mode` — it’s OK. What’s wrong with it?

**Comment by zxqfox** [comment]
Not sure it is right and documented. I described the issue)

**Comment by miripiruni** [comment]
I think this behaviour for backward capability.
