### ISSUE TITLE
Error while apply() inside match

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-xjst#309]
I don't think that it is good pattern but when you try to use apply inside match u get an Error:
[example](https://bem.github.io/bem-xjst/?bemhtml=block%28%27button%27%29%28%0A%20%20%20mode%28%27q%27%29%28function%28%29%20%7B%0A%20%20%20%20%20%20%20%20return%2042%3B%0A%20%20%20%7D%29%2C%0A%20%20%20%0A%20%20%20match%28function%20%28%29%7B%0A%20%20%20%20%20%20%20%20try%20%7B%0A%20%20%20%20%20%20%20%20%20%20return%20apply%28%27q%27%29%20%3D%3D%3D%2042%3B%0A%20%20%20%20%20%20%20%20%7D%20catch%20%28err%29%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log%28%27ERR%27%29%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20console.error%28err%29%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%29%28content%28%29%28function%28%29%20%7B%0A%20%20%20%20%20%20%20%20return%20apply%28%27q%27%29%3B%0A%20%20%20%20%7D%29%29%0A%20%20%20%0A%20%20%20%2Ctag%28%29%28function%28%29%20%7Breturn%20apply%28%27q%27%29%7D%29%0A%29%3B%0A%0A&bemjson=%28%7B%0A%20%20%20%20block%3A%20%27button%27%0A%7D%29%3B%0A)

Maybe we need to handle this error and continue to process template, or fix this.

**Comment by miripiruni** [comment]
We need a guard againgst recursion deadlock.

**Comment by miripiruni** [comment]
Think about cache for `apply('modeName')`.

**Comment by golyshevd** [comment]
Another example  https://goo.gl/EbKDW3

**Comment by miripiruni** [comment]
@golyshevd thank you. In current bem-xjst you can not use `apply()` in `match()`.

**Comment by golyshevd** [comment]
@miripiruni why not? is it feature? )

**Comment by miripiruni** [comment]
@golyshevd it happened :) I’ll try to fix it.

**Comment by golyshevd** [comment]
@miripiruni Thanks!

**Comment by remnev** [comment]
Guys, let's resurrect this issue. We encountered this problem again.

**Comment by miripiruni** [comment]
@remnev can you show your usecase please?

**Comment by golyshevd** [comment]
```js
block('foo')(
    mode('is-empty')(true),
    content()(
      match(() => !apply('is-empty'))('text')
    )
);
```

**Comment by remnev** [comment]
For example, I have a mode, which returns some data or nothing. Depends on it I want to output different content.
```js
// one case: returns "text"
block('foo')(
    mode('is-empty')(true),
    content()(
      '–',
      match(() => !apply('is-empty'))('text')
    )
);

// another case: returns "–"
block('foo').mod('a', 'b')(
    mode('is-empty')(false)
);
```

**Comment by miripiruni** [comment]
@remnev thanks.
