### ISSUE TITLE
Магия applyNext()

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-xjst#314]
> Конструкция applyNext возвращает результат работы следующего по приоритету шаблона в текущем режиме для текущего узла.

```js
block('link').tag()('a');
block('link').tag()(function() {
    var res = applyNext(); // res === 'a'
    return res;
});
```

Не совсем понятно как определяется приоритет. В голове лежит понятие, что под приоритетом принимается от частного к общему или снизу вверх?

```js
block('link').tag()('b');
block('link').tag()(function() {
    var res = applyNext(); // res === 'a'
    return res;
});
block('link').tag()('a');
```

так уже не правильно?

@tadatuta объяснял, что снизу вверх. Но как узнать что от `applyNext()` мы получили нужное содержимое.

Например вот такой код
```js
block('menu-item').content()(function () {
  let ctx = this.ctx
  let regax = new RegExp(`^${ctx.path}`)
  this.ctx.mods = { active: regax.test(this.data.url.path) }
  return {
    block: 'link',
    mix: [{ block: this.block, elem: 'link' }],
    url: `${ctx.path}`,
    content: ctx.content
  }
})
```
и его модификатор

```js
block('menu-item').mod('handler', 'events').content()((node, ctx) => {
  const content = applyNext()
  return [
    content,
    { elem: 'counter', content: 5 }
  ]
})
```

как модификатор узнаёт, что нужно из базового блока получить контент, а не из другого модификатора?

**Comment by zxqfox** [comment]
```
block('link').tag()('b');
block('link').tag()(function() {
    var res = applyNext(); // res === 'a'
    return res;
});
block('link').tag()('a');
```
У тебя место, где комментарий, не запускается в этом случае.
Останавливается на последней строчке, в остальные не заходит.

**Comment by zxqfox** [comment]
> как модификатор узнаёт, что нужно из базового блока получить контент, а не из другого модификатора?

Никак. В каком порядке приехали по депсам, в таком (точнее, обратном такому) и будут выполняться. Обычно сборка устроена так, что код для модификаторов приезжает после блока.
Если оба модификатора влияют на контент и при этом конфликтуют, то, очевидно, нужно либо перенести спорную логику в код самого блока, либо нужно написать дополнительный код, который будет запускаться при наличии обоих конфликтующих модификаторов, либо блок (/модификаторы) просто спроектированы неверно и стоит отказаться от одного из или даже обоих модификаторов в пользу чего-то иного.

**Comment by zxqfox** [comment]
http://goo.gl/wniZ8R вот смотри

**Comment by miripiruni** [comment]
@belozyorcev закрываем вопрос?

**Comment by belozyorcev** [comment]
@miripiruni  Да, в целом вроде уяснил.

**Comment by vithar** [comment]
@miripiruni может стоит дописать в документацию?

**Comment by belozyorcev** [comment]
В общем в первую очередь вызывается последний шаблон, который удовлетворяет условию и далее `applyNext()` по цепочке совпадений вверх?

**Comment by miripiruni** [comment]
@belozyorcev да. В документации именно это и написано:

> Шаблоны находятся в упорядоченном списке. Шаблоны проверяются в обратном порядке, то есть последние шаблоны приоритетнее первых (с учетом особенностей wildcard).

> Для каждого узла входного дерева шаблонизатор проверяет предикат каждого шаблона. Для этого выполняются все подпредикаты в контексте узла. Если все подпредикаты вернули true, дальнейший поиск шаблона прекращается и выполняется тело текущего.

> Если шаблон не найден, то будет использовано поведение по умолчанию.

https://github.com/bem/bem-xjst/blob/master/docs/ru/7-runtime.md#Как-выбираются-и-применяются-шаблоны


@vithar что именно предлагаешь добавить?

**Comment by belozyorcev** [comment]
@miripiruni 

Например:
шаблон1 -- подходит
шаблон2 - не подходит
шаблон3 - подходит
шаблон4 - не подходит
шаблон5 c applyNext - вызывает шаблон 3

Только в виде кода.

**Comment by miripiruni** [comment]
@belozyorcev 

Пример. Шаблоны:
```js
block('link')(
    tag()('a'), // 1 
    match(function() { return !this.ctx.url; }).tag()('span'), // 2
    tag()(function() {  // 3
        return applyNext();
    })
);
```

Входные данные:
```js
[
    { block: 'link'},
    { block: 'link', url: '/'}
]
```

Результат:
```html
<span class="link"></span> <!-- applyNext() в третьем шаблоне вернет результат вызова второго шаблона как предыдущего подходящего -->
<a class="link"></a> <!-- а в этом случае applyNext() вернет результат вызова первого шаблона как предыдущего подходящего -->
```

**Comment by belozyorcev** [comment]
@miripiruni да, так наглядней, и при этом лаконично :+1:

**Comment by miripiruni** [comment]
@belozyorcev вопрос еще актуален? Можно закрыть issue?

**Comment by belozyorcev** [comment]
@miripiruni нет. Разобрался :) А пример действительно крутой
