### ISSUE TITLE
Normalize mix

### ISSUE THREAD

**Issue by a-x-** [bem/bem-xjst#316]
Hey there,
Why bemhtml does not provide normalized `this.mix` (typed as `{BEMHTML[]}`)?

**Comment by miripiruni** [comment]
@a-x- what difference `this.mix` and `this.ctx.mix` you see?

**Comment by miripiruni** [comment]
@a-x- what you expect in normalized value?

**Comment by miripiruni** [comment]
@a-x- 

> expected: `this.mix` is always exist and typed as BEMJSON[]

Sounds reasonable. I’ll think about it.

**Comment by zxqfox** [comment]
Same feelings. I'm for it until performance will be affected.

**Comment by mishaberezin** [comment]
It would be very convenient if `this.mix` always existed in normalized form. Just yesterday received bug related to this.

**Comment by mishaberezin** [comment]
Of course if it could be implemented without significant performance tradeoff.

**Comment by miripiruni** [comment]
OK, I’ll try to check cost of this.

**Comment by a-x-** [comment]
### use cases
#### sytatic
common/foobar.bemhtml:
```js
block('foobar').mod('a','1').mix()({ block: 'bazqux' });
block('foobar').mod('a','2').mix()('happy-life-to-up-levels');
block('foobar').mod('a','3').content()('foobar');
```
desktop/foobar.bemhtml:
```js
block('foobar').mix()(function(){
    return applyNext().concat({block:'bem'})
});
```

in fact, safe desktop code is:

```js
block('foobar').mix()(function(){
    var mix = applyNext();
    if (!mix) {
        mix = [];
    } else if (Array.isArray(mix)) {
        mix = mix;
    } else if (mix.toString() === '[object Object]') {
        mix = [mix];
    } else if (typeof mix === 'string') {
        mix = [{ block: mix }];
    }
    mix.push({block:'bem'});
    console.log('mix', mix)
    return mix;
});
```

in practice, you may see next examples:
```js
block('service').elem('url').mix()(function() {
    var mix = applyNext() || [];

    // @FIXME: SAKHALIN-885
    // на уровне islands возвращается не массив
    if (!Array.isArray(mix) && mix) {
        mix = [mix];
    }

    mix.push({
        block: 'search2',
        elem: 'label'
    });
    return mix;
});
```

```js
block('b-page').match(function() {
    return !this.mods.pumpkin;
}).mix()(function() {
    var mixins = applyNext() || [];

    if (!_.isArray(mixins)) {
        mixins = [mixins];
    }

    mixins.push({
        block: 'i-cbir-controller'
    }, {
        block: 'i-cbir-initer',
        js: true
    });

    return mixins;
});
```

```js
    elem('popup').def()(function() {
        var ctx = this.ctx,
            mix = [{block: 'dropdown', elem: 'popup'}];

        ctx.mix && (mix = mix.concat(ctx.mix));
       // ...
    })
```

```js
block('images-touch-viewer').replace()(function() {
    var mix = this.ctx.mix || [], // а тут нельзя использовать `this.mix`
        mods = this.ctx.mods || {}; // тут можно использовать `this.mods`
    // ...
});
```

followed snippet is most used: `(this.ctx.mix || []).concat(...)`
in case of undefined mix: `this.ctx.mix && (ctx.mix = ctx.mix.concat(this.ctx.mix));`

**Comment by a-x-** [comment]
also, services (bemhtml users) use «Always enclose mixes in function and array literal» rule for self-safety and restful night

**Comment by a-x-** [comment]
I propose as a hacky perf solution followed trick:
Declare in any conf black list of bottleneck blocks of switched off `this.mix`

**Comment by miripiruni** [comment]
Look like relevant with #242

**Comment by a-x-** [comment]
Yep, but I disagree with creating helpers if we can normalize mix.

**Comment by miripiruni** [comment]
Since we have `addMix()` you should use it. The same for `addAttrs()`, `appendContent()`, `prependContent()`, `addJs()` and etc.

All magic with type checking, push(), extend and etc will perform `add*()` mode for you.
