### ISSUE TITLE
Benchmark and test on bem-components

### ISSUE THREAD

**Issue by indutny** [bem/bem-xjst#32]
n/t

**Comment by indutny** [comment]
showcase done: https://gist.github.com/indutny/d4b83e1bc5277bbffcd8

Results:

```
compile: 26ms
warmed up next
warmed up prev
next: 2294.6305644791187 RPS
prev: 1578.0337699226764 RPS
```

Looking good so far.

**Comment by indutny** [comment]
Other pages should be tested too.

**Comment by indutny** [comment]
Oh, also. There are some differences between `next.bemhtml` and `prev.bemhtml` at the moment. 

Summary of them:

* Always return content from template bodies (see https://github.com/bem/bem-xjst/issues/40)
* `match(this.ctx.prop)` does not work anymore
* `apply({ ... })` should be replaced by `local({...})(function() { return apply(); })`

**Comment by indutny** [comment]
Benchmark of bem-components/desktop.pages/index : https://gist.github.com/indutny/32d3206017302d306fab

Results:

```
compile: 27ms
warmed up next
warmed up prev
next: 1152.3392486748098 RPS
prev: 659.3696426216537 RPS
```

Fantastic!

**Comment by indutny** [comment]
Here are the timings for blown-up (16x times bigger content of `bem-components/desktop.pages/index`):

```
compile: 26ms
warmed up next
warmed up prev
next: 61.82380216383308 RPS ~ 16.175 ms
prev: 30.83279375944254 RPS ~ 32.433 ms
```

cc @veged

**Comment by narqo** [comment]
@indutny can you add info about the version of node.js / io.js that you'd been tested with. 

We've made a small research about the speed of current version of bem-xjst / bh and it turned out, that the results differ greatly (up to 150%) if we measure the same templates on 0.10/0.12 and io.js1.8

**Comment by indutny** [comment]
@narqo looks similar:

node.js v0.10.36:

```
compile: 7ms
warmed up next
warmed up prev
next: 51.698288786641164 RPS ~ 19.343 ms
prev: 32.18124477054773 RPS ~ 31.074 ms
```

io.js v2.0.0:

```
compile: 27ms
warmed up next
warmed up prev
next: 51.27416294928985 RPS ~ 19.503 ms
prev: 31.30576339104029 RPS ~ 31.943 ms
```

**Comment by narqo** [comment]
Hm, here is your gist (but with `next=false`) run on my machine:

~~~
varmbp £ ~/W/test-templates1 ⤳  master ±
  › node bench.js    # node v0.12.2
warmed up prev
prev: 253.83287643415576 RPS

varmbp £ ~/W/test-templates1 ⤳  master ±
  › iojs bench.js     # iojs v1.8.1
warmed up prev
prev: 422.3864836325238 RPS
~~~
