### ISSUE TITLE
Playground bug: ignores bemjson started not from 1th line

### ISSUE THREAD

**Issue by a-x-** [bem/bem-xjst#320]
Online demo: https://bem.github.io/bem-xjst 

Source code of online demo: https://github.com/bem/bem-xjst/tree/gh-pages

The problem: ignores bemjson started not from 1th line

|  |  |
| --- | --- |
| ![2016-07-28_20-18-58](https://cloud.githubusercontent.com/assets/6201068/17222368/f28b89d0-5508-11e6-9fac-279d1ba42f7e.png) | ![2016-07-28_20-19-08](https://cloud.githubusercontent.com/assets/6201068/17222372/f52ebff4-5508-11e6-81e8-712f208e2b8f.png) |

Possible solution: trim BEMJSON before `BEMHTML.apply(BEMJSON)`.

**Comment by zxqfox** [comment]
Короче, это `BlockStatement` и `Label`. Это не баг, но можно сделать фичу, чтобы можно было без внешних скобок писать bemjson.

**Comment by Yeti-or** [comment]
no 
it's seems that playground wraps code in () so it' bemjson not Label
just bad example
Problem from title still with us

**Comment by a-x-** [comment]
![2016-07-29_00-20-23](https://cloud.githubusercontent.com/assets/6201068/17229890/b476f6da-552a-11e6-90ce-c49be5912c82.png)
