### ISSUE TITLE
Add traditional jsdoc API page

### ISSUE THREAD

**Issue by a-x-** [bem/bem-xjst#329]
It's not api doc in my meaning: https://github.com/bem/bem-xjst/blob/master/docs/en/3-api.md

are exist something like this for bemhtml?: https://ru.bem.info/libs/bem-core/v2.8.0/desktop/i-bem/jsdoc/

**Comment by tadatuta** [comment]
https://github.com/bem/bem-xjst/blob/master/docs/en/5-templates-syntax.md ?

**Comment by a-x-** [comment]
cool, thanks!

it remains to rename it and add link to readme and bem.info
