### ISSUE TITLE
Docs: BEMTREE landing

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#332]
Цитирую обращение пользователя @tadatuta 

> я только что в очередной раз поймал себя на том, что с новой докой на bem-xjst некуда давать ссылку на историю про BEMTREE.
> 
> раньше была отдельная дока про BEMTREE и дока про двухуровневую шаблонизацию в целом. они были протухшие и сложные, но хоть были.
> 
> Слав, ты можешь в своей фирменной манере человекопонятного повествования написать такую? А то я пока кидаю людям вот это: https://github.com/tadatuta/bem-bemtree-static-project-stub/blob/master/README.ru.md

**Comment by miripiruni** [comment]
@tadatuta @vithar it is right that I can not use this modes?

## attrs()
Template:`block('b').attrs()({ id: 'test' })`.
Input BEMJSON: `{ block: 'b' }`.

Expected output BEMJSON: `{ block: 'b', attrs: { id: 'test' } }`.
Actual output BEMJSON: `{ block: 'b' }`.

## mix()
Template:`block('b').mix()('mixed')`.
Input BEMJSON: `{ block: 'b' }`.

Expected output BEMJSON: `{ block: 'b', mix: { block: 'mixed' } }`.
Actual output BEMJSON: `{ block: 'b' }`.

## js()
Template:`block('b').js()(true)`.
Input BEMJSON: `{ block: 'b' }`.

Expected output BEMJSON: `{ block: 'b', js: true }`.
Actual output BEMJSON: `{ block: 'b' }`.

## bem()
Template:`block('b').bem()(true)`.
Input BEMJSON: `{ block: 'b' }`.

Expected output BEMJSON: `{ block: 'b', bem: true }`.
Actual output BEMJSON: `{ block: 'b' }`.

## cls()
Template:`block('b').cls()('my-custom-html-class')`.
Input BEMJSON: `{ block: 'b' }`.

Expected output BEMJSON: `{ block: 'b', cls: 'my-custom-html-class' }`.
Actual output BEMJSON: `{ block: 'b' }`.

**Comment by miripiruni** [comment]
@tadatuta @vithar ping

**Comment by miripiruni** [comment]
Related comment: https://github.com/bem/bem-xjst/issues/181#issuecomment-194799564

**Comment by vithar** [comment]
I think we can add these mods to bemtree.

**Comment by miripiruni** [comment]
Good

**Comment by tadatuta** [comment]
Oh, I lost this issue for some reason.

It was done on purpose: BEMTREE is just about data and these mods are about HTML output. All these fiels can be easily set in parent.
So I vote against it:
1. It will make BEMTREE slower
2. It will be even harder for users to decide which template to choose

**Comment by miripiruni** [comment]
@tadatuta but how I can write templates where I need to add mix or attrs to BEMJSON?

**Comment by tadatuta** [comment]
обычно у тебя есть корневой блок — точка входа, который кладет в себя новые блоки, а те, в свою очередь, своих чайлдов и так далее.
и вот каждый раз, когда ты создаешь чайлдов, можно указывать не только их имя, модификаторы и нужные им данные, но и миксы с атрибутами.
вообще, в большинстве случаев сам блок не должен отвечать за миксы с другими сущностями. это задача родителя, который знает, что вот этот импут — не только блок `input`, но еще и элемент формы. если только эти миксы не про оформление (типа смиксовать с `clearfix`), но такому место в BEMHTML, как, собственно, и атрибутам.
да, есть редкие кейсы, когда это оправдано, но в этом случае пользователь сможет сделать `this.extendCtx({ mix: 'b2' })`.

**Comment by miripiruni** [comment]
@tadatuta `this.extendCtx()` сейчас не существует…

**Comment by miripiruni** [comment]
@tadatuta хорошо, давайте на встрече голосом этот решим по этой задаче.

**Comment by miripiruni** [comment]
Closed in favor of https://github.com/bem/bem-xjst/issues/362
