### ISSUE TITLE
Docs: BEMTREE

### ISSUE THREAD

**Issue by belozyorcev** [bem/bem-xjst#335]
https://ru.bem.info/platform/bem-xjst/templates-syntax/#bemtree-1

> Движком BEMTREE используются только режимы def и content. Пользовательские режимы тоже могут быть использованы. Остальные режимы, описанные в документации выше, применимы только к BEMHTML.

Создаётся ощущение, что в BEMTREE нельзя использовать режимы-хэлперы (в частности replace).

**Comment by miripiruni** [comment]
Related: #332

**Comment by miripiruni** [comment]
Fixed.
