### ISSUE TITLE
Matching for "block mod + elem" not work

### ISSUE THREAD

**Issue by 4ok** [bem/bem-xjst#343]
block('block-name').mod('mod-name', 'mod-val').elem('elem-name')

This construction not work

**Comment by miripiruni** [comment]
1. bem-xjst version?
2. Can you provide example with template, benjson and result? You can use online demo for sharing code snippet: https://bem.github.io/bem-xjst

**Comment by miripiruni** [comment]
@4ok https://github.com/bem/bem-xjst/blob/master/CHANGELOG.md#2016-01-29-v500-miripiruni It’s not about this?

**Comment by miripiruni** [comment]
@4ok ping

**Comment by miripiruni** [comment]
Feel free to reopen if it’s not clear.

**Comment by 4ok** [comment]
@miripiruni not it

**Comment by 4ok** [comment]
I'm sorry for the delay

---------------------------------------------

Bem-xjst version: `7.0.4`

This construction is not work if elem is inside of the another block, for example it is inside of 'block-name-inside'

----------------------------------------------

Bemjson:

```js
{
    block : 'block-name',
    mods : {
        'mod-name' : 'mod-val'
    },
    content : [
        {
            block : 'block-name-inside',
            content : [
                {
                    block : 'block-name',
                    elem : 'elem-name',
                }
            ]
        }
    ]
}
```

Bemhtml:

```js
block('block-name').mod('mod-name', 'mod-val').elem('elem-name')(
    content('THIS CONSTRUCTION IS NOT WORK')
)
```

**Comment by 4ok** [comment]
Sorry I understand. it was necessary to add mix to child block. This [work example](https://bem.github.io/bem-xjst/?bemhtml=block(%27block-name%27).mod(%27mod-name%27%2C%20%27mod-val%27).elem(%27elem-name%27)(%0A%20%20%20%20content()(%27THIS%20CONSTRUCTION%20IS%20NOT%20WORK%27)%0A)&bemjson=(%7B%0A%20%20%20%20block%20%3A%20%27block-name%27%2C%0A%20%20%20%20mods%20%3A%20%7B%0A%20%20%20%20%20%20%20%20%27mod-name%27%20%3A%20%27mod-val%27%0A%20%20%20%20%7D%2C%0A%20%20%20%20content%20%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20block%20%3A%20%27block-name-inside%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20content%20%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20block%20%3A%20%27block-name%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20mods%20%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27mod-name%27%20%3A%20%27mod-val%27%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20elem%20%3A%20%27elem-name%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%5D%0A%7D)).
