### ISSUE TITLE
Let's prohibit .b_mod_val1.b_mod_val2

### ISSUE THREAD

**Issue by a-x-** [bem/bem-xjst#350]
Examples in the wild:
* `.serp-item_type_search.serp-item_type_market` https://yandex.ru/images/search?text=окна&comm=1
* `.suggest2-item__text_type_green-url.suggest2-item__text_type_url` https://yandex.ru/images/touch/search?text=bmw.com

[demo](https://goo.gl/ktLiiv)
```js
{
    block: 'b',
    mods: {mod:1},
    mix: [{mods:{mod:2}}]
}
```

#### todo
* add warning
* deprecate it
* prohibit completely in the future versions

**Comment by miripiruni** [comment]
https://github.com/bem/bem-xjst/releases/tag/v7.3.1
