### ISSUE TITLE
Report for duplicates in class names in dev mode

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#359]
Guess like we 

Also this reporting could be useful for modifiers set on block with 2 or more values: b_m_v1 v_m_v2 etc.
Like that: `{block: 'b', mods: {m: 'v1'}, mix: {mods: {m: 'v2'}}`

**Comment by miripiruni** [comment]
Fixed in v7.3.1.

https://github.com/bem/bem-xjst/pull/352/commits

**Comment by zxqfox** [comment]
Ah, sorry. ;-( and thanks!
