### ISSUE TITLE
BEMTREE: introduce js(), mix(), mods() and elemMods() modes

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#362]
~~After discussion in https://github.com/bem/bem-xjst/issues/332 we decided to introduce new modes in BEMTREE.~~

We dicieded to introduce only data related modes (not HTML related).

**Comment by miripiruni** [comment]
It is useful to @collapsus for example

**Comment by miripiruni** [comment]
The plan: no difference with modes with BEMTREE and BEMHTML, only output format diff (bemjson, html).

**Comment by tadatuta** [comment]
Let me try once again: I don't think these mods are useful enough for BEMTREE and moreover they are kinda harmful: user just should not set such things like attributes, classes, etc in BEMTREE — it's all about HTML. And extra modes will make BEMTREE slower.

Is there really strong arguments for it?

**Comment by vithar** [comment]
I agree with @tadatuta

**Comment by tadatuta** [comment]
We talked with @collapsus and decided it should be enough to add just `js()` mode which is widely used for blocks with models, i.e. the list of modes in BEMTREE should be following:
* `def()` + `extend()`, `replace()` and `wrap()` helpers
* `content()`
* `js()`

**Comment by miripiruni** [comment]
@tadatuta can you show example of `js()` usage?

**Comment by collapsus** [comment]
not for models
```(javascript)
    js: {
        var currenciesDescription = this.data.currencies_description,
            currencies  = {};

        Object.keys(currenciesDescription).map(function(key) {
            currencies[key] = currenciesDescription[key].full_name;
        });

        return {
            currencies: currencies
        };
    }
```

for models
```(javascript)
    js: {
        modelName: 'm-autopay-settings',
        modelData: this.modelData
    }
```
