### ISSUE TITLE
&lt;!DOCTYPE html&gt;

### ISSUE THREAD

**Issue by Maksimenka** [bem/bem-xjst#383]
Экранируются кавычки в  поле doctype, как я понимаю так быть не должно. Данная ситуация наблюдается с версии 8.х bem-xjst.
Сори за ссылку, так и не понял как ее тут укоротить.
https://bem.github.io/bem-xjst/?bemhtml=block(%27page%27)(%0D%0A%0D%0A%20%20%20%20wrap()(function()%20%7B%0D%0A%20%20%20%20%20%20%20%20var%20ctx%20%3D%20this.ctx%3B%0D%0A%20%20%20%20%20%20%20%20this._nonceCsp%20%3D%20ctx.nonce%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20return%20%5B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20ctx.doctype%20%7C%7C%20%22%3C!DOCTYPE%20html%3E%22%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tag%20%3A%20%27html%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20cls%20%3A%20%27ua_js_no%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20content%20%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20elem%20%3A%20%27head%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20content%20%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20tag%20%3A%20%27meta%27%2C%20attrs%20%3A%20%7B%20charset%20%3A%20%27utf-8%27%20%7D%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20ctx.uaCompatible%20%3D%3D%3D%20false%3F%20%27%27%20%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tag%20%3A%20%27meta%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20attrs%20%3A%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%27http-equiv%27%20%3A%20%27X-UA-Compatible%27%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20content%20%3A%20ctx.uaCompatible%20%7C%7C%20%27IE%3Dedge%27%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20tag%20%3A%20%27title%27%2C%20content%20%3A%20ctx.title%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20block%20%3A%20%27ua%27%2C%20attrs%20%3A%20%7B%20nonce%20%3A%20ctx.nonce%20%7D%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20ctx.head%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20ctx.styles%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20ctx.favicon%3F%20%7B%20elem%20%3A%20%27favicon%27%2C%20url%20%3A%20ctx.favicon%20%7D%20%3A%20%27%27%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20ctx%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20%5D%3B%0D%0A%20%20%20%20%7D)%2C%0D%0A%0D%0A%20%20%20%20tag()(%27body%27)%2C%0D%0A%0D%0A%20%20%20%20content()(function()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%5B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20applyNext()%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.ctx.scripts%0D%0A%20%20%20%20%20%20%20%20%5D%3B%0D%0A%20%20%20%20%7D)%2C%0D%0A%0D%0A%20%20%20%20elem(%27head%27)(%0D%0A%20%20%20%20%20%20%20%20bem()(false)%2C%0D%0A%20%20%20%20%20%20%20%20tag()(%27head%27)%0D%0A%20%20%20%20)%2C%0D%0A%0D%0A%20%20%20%20elem(%27meta%27)(%0D%0A%20%20%20%20%20%20%20%20bem()(false)%2C%0D%0A%20%20%20%20%20%20%20%20tag()(%27meta%27)%0D%0A%20%20%20%20)%2C%0D%0A%0D%0A%20%20%20%20elem(%27link%27)(%0D%0A%20%20%20%20%20%20%20%20bem()(false)%2C%0D%0A%20%20%20%20%20%20%20%20tag()(%27link%27)%0D%0A%20%20%20%20)%2C%0D%0A%0D%0A%20%20%20%20elem(%27favicon%27)(%0D%0A%20%20%20%20%20%20%20%20bem()(false)%2C%0D%0A%20%20%20%20%20%20%20%20tag()(%27link%27)%2C%0D%0A%20%20%20%20%20%20%20%20attrs()(function()%20%7B%20return%20%7B%20rel%20%3A%20%27shortcut%20icon%27%2C%20href%20%3A%20this.ctx.url%20%7D%3B%20%7D)%0D%0A%20%20%20%20)%0D%0A%0D%0A)%3B%0D%0A&bemjson=(%0D%0A%20%20%20%20%5B%7B%0D%0A%20%20%20%20block%20%3A%20%27page%27%2C%0D%0A%20%20%20%20doctype%3A%20%27%3C!DOCTYPE%20html%3E%27%2C%0D%0A%20%20%20%20title%20%3A%20%27%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B9%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20html%2Fhead%2Fbody-%D0%BE%D0%B1%D0%B2%D1%8F%D0%B7%D0%BA%D0%B8%20%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B%27%2C%0D%0A%20%20%20%20favicon%20%3A%20%27%2F%2Fbem.info%2Ffavicon.ico%27%2C%0D%0A%20%20%20%20head%20%3A%20%5B%0D%0A%20%20%20%20%20%20%20%20%7B%20elem%20%3A%20%27css%27%2C%20url%20%3A%20%2710-simple.css%27%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%7B%20elem%20%3A%20%27js%27%2C%20url%20%3A%20%2710-simple.js%27%20%7D%2C%0D%0A%20%20%20%20%20%20%20%20%7B%20elem%20%3A%20%27meta%27%2C%20attrs%20%3A%20%7B%20name%20%3A%20%27keywords%27%2C%20content%20%3A%20%27BEM%27%20%7D%20%7D%0D%0A%20%20%20%20%5D%2C%0D%0A%20%20%20%20content%20%3A%20%7B%20block%20%3A%20%27bla%27%2C%20content%20%3A%20%27%D0%9F%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B9%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20%D0%BE%D0%B1%D0%B2%D1%8F%D0%B7%D0%BA%D0%B8%20%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B%27%20%7D%0D%0A%7D%5D%0D%0A)

**Comment by miripiruni** [comment]
https://goo.gl/hSqstF

См. документацию: [Если вам нужно вывести строку без экранирования…](https://github.com/bem/bem-xjst/blob/master/docs/ru/3-api.md#%D0%AD%D0%BA%D1%80%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)

**Comment by Maksimenka** [comment]
Я исходил из готовых решений библиотеки, bem-core, итог, со старта такой баг.

**Comment by miripiruni** [comment]
@Maksimenka тогда откуда такой код как у тебя? Вот [исходники bem-core](https://github.com/bem/bem-core/blob/v3/common.blocks/page/page.bemhtml.js#L4). И там есть обвязка `{ html: … }`.

**Comment by Maksimenka** [comment]
Видимо отсюда: https://github.com/bem/bem-components/blob/v4/bower.json

**Comment by miripiruni** [comment]
@tadatuta посмотри, пожалуйста.

**Comment by yar-usenko** [comment]
bem-components еще не потдерживает bem-xjst 8.х
https://github.com/bem/bem-components/issues/1942

**Comment by miripiruni** [comment]
@tadatuta может написать об этом явно прямо в Readme?

**Comment by tadatuta** [comment]
Я скорее хочу таки сделать поддержку bem-xjst 8.

**Comment by miripiruni** [comment]
@tadatuta там много работы осталось? Можешь оценить в часах?

**Comment by tadatuta** [comment]
чистого времени — немного, но реально доберусь не раньше, чем на выходных
