### ISSUE TITLE
Online demo: get parameters for version

### ISSUE THREAD

**Issue by miripiruni** [bem/bem-xjst#389]
In online demo we need to be able save in URL version and engine of current demo state.

**Comment by vitkarpov** [comment]
@miripiruni Let me make it clear a little bit a use case:

- change version and engine
- send the current url to other person
- the other person can see the same screen as I have

Is this correct?

**Comment by miripiruni** [comment]
@vitkarpov yep

**Comment by vitkarpov** [comment]
Okay, thanks! Then I think the bootstrap scenario should be rebuild. 

**Now**

We load the latest version of engine during the first load (script right inside first html). When user picks another version from select, we load the corresponding script asynchronously and change the editors.

**Then**

We load nothing during the first load, when url parsed and we know the current version (it could be default, from demo block params, if it's not specified in the url) we should load the script and goes the same way if user picks the version from select.

What do you think about it?

**Comment by miripiruni** [comment]
@vitkarpov I think it’s good decision. First of all we need to figure out which version and engine needed and then load it.

**Comment by vitkarpov** [comment]
Super cool, trying to implement then :)
