### ISSUE TITLE
Share link - bug - ранее созданная ссылка работает с ошибкой

### ISSUE THREAD

**Issue by ilyar** [bem/bem-xjst#413]
### Input code or something about issue background

Ранее созданная ссылка (Share link) работает с ошибкой, не вставляется шаблон.

**Share link**
`https://goo.gl/w4vq0a`

**Data**
`https://miripiruni.github.io/bem-xjst/?bemhtml=&bemjson=(%7B%0A%20%20tag%20%3A%20%27div%27%2C%0A%20%20attrs%20%3A%20%7B%0A%20%20%20%20id%20%3A%20%27anchor1%27%2C%0A%20%20%20%20name%20%3A%20%27BEM%27%2C%0A%20%20%7D%2C%0A%20%20content%20%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20tag%20%3A%20%27div%27%2C%0A%20%20%20%20%20%20attrs%20%3A%20%7B%0A%20%20%20%20%20%20%20%20id%20%3A%20%27anchor2%27%2C%0A%20%20%20%20%20%20%20%20name%20%3A%20%27BEM%202%27%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20content%20%3A%20%27BEM%20text%27%0A%20%20%20%20%7D%2C%0A%20%20%5D%0A%7D)%3B`

### Expected Behavior

Шаблон из сохраненной ссылки вставляется в поле шаблона, он в ссылке не задан, поле шаблона д.б. пустым.

### Actual Behavior

Шаблон из сохраненной ссылки подменяется шаблоном из демо по умолчанию.

### Possible Solution

Где-то надо починить разбор данных из ссылки. 

~Подскажите куда смотреть попробую починить.~
Примерно тут https://github.com/bem/bem-xjst/blob/gh-pages/common.blocks/demo/demo.js#L90

> Мы изменили имя параметра с BEMHTML на templates, потому что появилась возможность писать BEMTREE шаблоны. Нужно поддержать оба имени параметра.

### Your Environment

https://miripiruni.github.io/bem-xjst (8.x-rc)

**Comment by miripiruni** [comment]
@ilyar примерно сюда https://github.com/bem/bem-xjst/blob/gh-pages/common.blocks/demo/demo.js#L90

Мы изменили имя параметра с BEMHTML на templates, потому что появилась возможность писать BEMTREE шаблоны. Нужно поддержать оба имени параметра.

**Comment by ilyar** [comment]
Понял, буду смотреть, уточнил данные (сейчас происходит подмена оригинальных данных).

**Comment by miripiruni** [comment]
@ilyar кстати, обрати внимание, что в тексте этого issue у тебя ссылка на https://miripiruni.github.io/bem-xjst — а это мой форк, а не официальная песочница https://bem.github.io/bem-xjst. Мой фокр отстал и я вообще его удалю за ненадобностью.

**Comment by ilyar** [comment]
учту, спасибо.
