### ISSUE TITLE
Thin core for BEMJSON

### ISSUE THREAD

**Issue by hcodes** [bem/bem-xjst#417]
Для клиентских скриптов хотелось бы иметь легковесную версию для генерации HTML из BEMJSON без шаблонов и в виде отдельного пакета.

**Comment by miripiruni** [comment]
@hcodes не уверен что ты называешь «легковесной версией», но сейчас можно сгенерировать runtime core с помощью метода `generate`. См. раздел [создание бандла](https://github.com/bem/bem-xjst/blob/master/docs/ru/3-api.md#%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D0%B0%D0%BD%D0%B4%D0%BB%D0%B0). Если не передавать аргументов, то шаблонов не будет как ты хочешь.

**Comment by miripiruni** [comment]
Обсудили еще раз но телефону. Идея такая: сделать вариант движка без возможности добавлять шаблоны, но с наименьшим объёмом кода.

**Comment by tadatuta** [comment]
https://github.com/floatdrop/bemjson-to-html

**Comment by miripiruni** [comment]
@tadatuta cool! But definitely we need more tests

Compare:
1) https://github.com/floatdrop/bemjson-to-html/tree/master/test 
2) https://github.com/bem/bem-xjst/tree/master/test (see `bemjson-*` filenames)

**Comment by arikon** [comment]
Closed in favor of https://github.com/floatdrop/bemjson-to-html
