### ISSUE TITLE
Runtime lint: mods and elemMods must be string or number or boolean

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-xjst#420]
for example I was confused with all bem* formats and write something like that:
```
({ block: 'popup', mods: { theme: ['normal', 'action'] } })
```
I will get `<div class="popup popup_theme_normal,action"></div>`

In big project I can even don't notice this mistake.

What about dev and production build of bem-xjst?
So in dev I will get Error about wrong format of bemjson Node.

Or you have already have such solution? If so, why not include it in bem-xjst demo stand?

**Comment by miripiruni** [comment]
@Yeti-or use runtimeLint option https://github.com/bem/bem-xjst/tree/master/runtime-lint

I’ll add you case to check list. `mods` and `elemMods` must be `string` or `number` or `boolean`.

**Comment by Yeti-or** [comment]
@miripiruni does demo bem.github.io/bem-xjst run with runtime lint option?

**Comment by miripiruni** [comment]
@Yeti-or No. In the demo you can not choose options. [PRs](https://github.com/bem/bem-xjst/issues/392) are welcome ;)
