### ISSUE TITLE
appendContent/prependContent escapes html

### ISSUE THREAD

**Issue by golyshevd** [bem/bem-xjst#422]
bemjson
```js
{
    block: 'foo'
}
```

bemhtml
```js
block('foo')(
    prependContent()(() => ({
        elem: 'x', 
        content: 'before'
    })),
    appendContent()(() => ({
        elem: 'x', 
        content: 'after'
    }))
);
```

result
```html
<div class="foo">&lt;div class="foo__x"&gt;before&lt;/div&gt;&lt;div class="foo__x"&gt;after&lt;/div&gt;</div>
```

Live example https://goo.gl/5wXovY

---------

guess appendContent/prependContent is just sugar for `content` + `applyNext`, but this behaviour is unexpected

**Comment by miripiruni** [comment]
BTW, in this case you don’t need use arrow function at all.

```
block('foo')(
    prependContent()({
        elem: 'x', 
        content: 'before'
    }),
    appendContent()({
        elem: 'x', 
        content: 'after'
    })
);
```

I detect that bug exists only with arrow function…

**Comment by zxqfox** [comment]
Same with usual functions: https://goo.gl/82s0Hr

**Comment by miripiruni** [comment]
@zxqfox of course. And [I fixed it already](https://github.com/bem/bem-xjst/pull/425/files#diff-66d1c3a97e2c7875ecf077e0089d5b27R53).
