### ISSUE TITLE
no documentation about templating values inside attrs hash

### ISSUE THREAD

**Issue by Yeti-or** [bem/bem-xjst#423]
You could do this, but this is undocumented, and I couldn't find test for this API. So
what about drop it??

```
{ 
    block: 'button', 
    attrs: {
        // this works
        name: {block: 'i-bem', elem: 'i18n', keyset: 'attach', key: 'button-text'},
    }
}
```

**Comment by miripiruni** [comment]
Why it’s important for you?

**Comment by Yeti-or** [comment]
@miripiruni It's important because it is undocumented =)
but for me, because of this project: https://github.com/bem-sdk/bemjson-to-decl

**Comment by miripiruni** [comment]
Fixed: https://github.com/bem/bem-xjst/blob/master/docs/en/4-data.md#attrs
