### ISSUE TITLE
Possible memory leak in Match.exec() in 4.x branch

### ISSUE THREAD

**Issue by SlNPacifist** [bem/bem-xjst#433]
Here is current 4.x exec function:
```javascript
Match.prototype.exec = function exec(context) {
  var save = this.checkDepth();
  ...
  if (i === this.count)
    return undefined;
  ...
  this.restoreDepth(save);
};
```

In some cases `checkDepth` increases `this.maskOffset`, but `restoreDepth` is not called afterwards, since no match was found.
This leads to increasing of `this.maskOffset` and `this.mask` array.

**Comment by miripiruni** [comment]
Also this fix is released in v8.6.10
