### ISSUE TITLE
Any ways to extend syntax?

### ISSUE THREAD

**Issue by JiLiZART** [bem/bem-xjst#438]
Is there any ways to add your own syntax functions?

e.g. if i have idea of some sort iteration support

template
```js
block('links')(
    eachOf(function () {
        return this.ctx.items
    })(
        tag()('a'),
        content()(function () {
            return this.ctx.text
        })
    )
);
```

for data
```js
{
    block: 'links',
    items: [
        {text: 'one'},
        {text: 'two'}
    ]
}
```

Or only way is to PR this feature in core code?

**Comment by miripiruni** [comment]
@JiLiZART I do not understand why you need `eachOf()`. bem-xjst have built-in tree traversal.

Example: https://goo.gl/4NBAvL
