### ISSUE TITLE
Escaping values in modifiers in block/elem names

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#451]
### Input code or something about issue background
https://goo.gl/0W8Ce5

и
```js
[{
  block: 'b',
  mods: { v: 'hacked"><script>alert(1);</script><br x="' }
}]
```

### Expected Behavior
Modifiers safely escaped

### Actual Behavior
HACKED

### Possible Solution
Escape or trim insecure characters in mod values, warn about insecure mod values in dev mode

### Your Environment
Any bem-xjst version

**Comment by miripiruni** [comment]
> goo.gl shortlink has been disabled. It was found to be violating our Terms of Service. Click here and here for more information about our terms and policies respectively.

:(

**Comment by zxqfox** [comment]
> :(

fixed

**Comment by miripiruni** [comment]
`block` name, `elem` name, `mod` name and values are trusted fields. These fields must be checked by the developer. Not by bem-xjst.

Developers must clearly know what data provided to `block`, `elem` and `mods` fields. If the data is user generated content then developer must escape it manually.

**Comment by miripiruni** [comment]
> warn about insecure mod values in dev mode

We can rearange this issue to «Runtime lint: check insecute block, elem, mod values in dev mode» if you provide cases.

We already have checks [for wrong naming](https://github.com/bem/bem-xjst/blob/master/runtime-lint/stand.js#L67-L79).

**Comment by zxqfox** [comment]
> If the data is user generated content then developer must escape it manually.

-1

> We can rearange this issue to «Runtime lint: check insecute block, elem, mod values in dev mode»

ok ;-)
