### ISSUE TITLE
Добавить информацию о версии bemxjst

### ISSUE THREAD

**Issue by belozer** [bem/bem-xjst#452]
Заметил, что в доке https://ru.bem.info/platform/bem-xjst/templates-syntax/ есть много примеров с `bemxjst@v8`, но вот только что это доступно начиная с 8-й версии нигде не заметил. Это вводит многих в заблуждение. Приходится пояснять, почему данный синтаксис не работает в 7-й версии.

--------------------------
Для того, чтобы добавить attrs, вы можете использовать режим addAttrs(), который является сокращением режима attrs() и выглядит более лаконично:
```
addAttrs()({ id: 'test', name: 'test' }); // Это полностью эквивалентно следующему:
attrs()(function() {
    var attrs = applyNext() || {}; // атрибуты из предыдущих шаблонов или BEMJSON-а
    return this.extend(attrs, { id: 'test', name: 'test' });
});
```
> Памятка: режим addAttrs() доступен начиная с bemxjst 8.
--------------------------
Что думаете по этому поводу?

**Comment by miripiruni** [comment]
@vithar @tadatuta я вам говорил, что на bem.info невозможно понять на документацию какой версии смотришь. У вас есть таск в bem.info про это?

**Comment by miripiruni** [comment]
@belozer я закрыл этот issue и перенес его в трекер задач bem.info, который не доступен публично.
