### ISSUE TITLE
Баг или нормальное поведение у match

### ISSUE THREAD

**Issue by belozer** [bem/bem-xjst#460]
bemjson
```js
([
  { block: 'link', mods : {a : 2 }, a : 4}
]);
```
bemhtml
```js
block('link')(
    content()((node, ctx) => [
        {
            elem : 's'
        },
    ]),
    
    elem('s')(
        content()((node, ctx) => [
            {
                block : 'c'
            }
        ])
    ),
    
    match((node, ctx) => ctx.a)(
        elem('s')(
            content()((node, ctx) => [
                applyNext(),
                {
                    block : 'c3',
                    content : ctx.a
                }
            ])
        ),
        
        content()((node, ctx) => [
            applyNext(),
            {
                block : 'c2',
                content : ctx.a
            }
        ])
    )
);
```

HTML
```html
<div class="link link_a_2">
    <div class="link__s">
        <div class="c"></div>
    </div>
    <div class="c2">4</div>
</div>
```

В content элемента `s` ничего не добавилось.
Если матчится на mod, то всё норм.

```js
block('link')(
    content()((node, ctx) => [
        {
            elem : 's'
        },
    ]),
    
    elem('s')(
        content()((node, ctx) => [
            {
                block : 'c'
            }
        ])
    ),
    
    mod('a')(
        elem('s')(
            content()((node, ctx) => [
                applyNext(),
                {
                    block : 'c3',
                    content : ctx.a
                }
            ])
        ),
        
        content()((node, ctx) => [
            applyNext(),
            {
                block : 'c2',
                content : ctx.a
            }
        ])
    )
);
```

HTML
```html
<div class="link link_a_2">
    <div class="link__s">
        <div class="c"></div>
        <div class="c3"></div>
    </div>
    <div class="c2">4</div>
</div>
```

**Comment by belozer** [comment]
//cc @miripiruni

**Comment by zxqfox** [comment]
`block('link').match((node, ctx) => ctx.a).elem('s')(...)` эквивалент `block('link').elem('s').match((node, ctx) => ctx.a)(...)` — в каком контексте запускается?
`block('link').mod('a').elem('s')(...)` — и что проверяет `mod` (не `elemMod`)?

**Comment by miripiruni** [comment]
@belozer я не понял твоего вопроса:

> В content элемента s ничего не добавилось.

Потому что в контент элемента `s` добавился блок `c`. Я это вижу [в песочнице](https://goo.gl/AyGnwW).

Ты можешь сформировать минимальный пример кода и сформулировать вопрос в стандартном виде: сделал то-то, ожидал получить то-то, но получил вот это…

**Comment by zxqfox** [comment]
@belozer В общем, ошибка в твоем коде, bem-xjst правильно отработал. Ты сам это поймешь, когда разберешься с указанными мной строчками. :-)

И спасибо за бдительность!

**Comment by miripiruni** [comment]
> ошибка в твоем коде

какая ошибка?

**Comment by miripiruni** [comment]
Вообще на такие случаи всяких непонятных комбинаций шаблонов всегда рекомендую использовать `console.log`, чтобы понять кто-кого переопределил, и кто в каком порядке отрабатывает.

**Comment by zxqfox** [comment]
> какая ошибка?

Я сверху же написал :-)

ctx.a находится у блока, а проверяется у элемента

**Comment by belozer** [comment]
@zxqfox да, вроде дошло :+1:  спасибо за разъяснение :)
