### ISSUE TITLE
Use widely known @bem/sdk.naming for generating classes

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-xjst#469]
### Input code or something about issue background
Run in shell:
```sh
node -p "require('bem-xjst').bemhtml.compile('',{naming:{mod: '--',val:'_'}}) \
.apply({block:'button',mods:{mod:'val'}})"
```

### Expected Behavior
```html
<div class="button button--mod_val"></div>
```

### Actual Behavior
```html
<div class="button button--mod--val"></div>
```

### Possible Solution
Usage of @bem/sdk.naming.entity.stringify

### Your Environment
```sh
$ echo $SHELL
/usr/local/bin/fish
$ node -v
v4.5.0
$ bem-xjst -v
8.7.0
```

**Comment by miripiruni** [comment]
In current version there is no `val` option. You can choose `elem` separator and `mod` separator only. 

I’m against using external libraries such as sdk.naming since we have matric for client bundle size.

**Comment by miripiruni** [comment]
@zxqfox I suggest PR #470. Would you happy with that?

**Comment by zxqfox** [comment]
@miripiruni Yes for now. I'll be here later when we'll finish `@bem/sdk` core modules 😼
