### ISSUE TITLE
Benchmark on large real projects

### ISSUE THREAD

**Issue by indutny** [bem/bem-xjst#47]
Find out the numbers for different number of templates:

* Small (10-20)
* Medium (~100)
* Awfully big (> 1000)

**Comment by indutny** [comment]
Also, don't forget to benchmark the compilation time itself.

**Comment by indutny** [comment]
@vkz we have base for this in the project file tree now. Check out `benchmarks/` folder ;)

**Comment by miripiruni** [comment]
So, I already commit [new showcases](https://github.com/bem/bem-xjst/tree/master/bench/templates):
1) granny — ~100 templates.
2) serp — ~1000 templates.

It’s real production templates and BEMJSON.
