### ISSUE TITLE
ul and ol end tags are NOT optional in HTML

### ISSUE THREAD

**Issue by vithar** [bem/bem-xjst#472]
ul and ol marked as optional in this list:

https://github.com/bem/bem-xjst/blob/58916ebf0546ac3c84dd285ac43b9fa6bb8e5f51/lib/bemhtml/index.js#L121

But according to html spec its end tags NOT optional:

https://www.w3.org/TR/html4/index/elements.html

**Comment by miripiruni** [comment]
Fixed
