### ISSUE TITLE
bem-xjst v7.x extend mods bug

### ISSUE THREAD

**Issue by belozer** [bem/bem-xjst#489]
input bemjson
```
([
  { block: 'link', c : 2 },
]);
```

template

```
block('link')(

    match((node, ctx) => ctx.c)
        .extend()((node, ctx) => ({
            'ctx.mods' : node.extend(ctx.mods, { cancelled : true } )
        }))
);

block('link').mod('cancelled')(
    content()('ssss')    
);
```

output (bemtree v7.x)
```
[
	{
		"block": "link",
		"c": 2,
		"content": "ssss"
	}
]
```

output (bemtree v8.x)
```
[
	{
		"block": "link",
		"c": 2,
		"mods": {
			"cancelled": true
		},
		"content": "ssss"
	}
]
```

In bemtree v7.x, mods not extended (but content works).

**Comment by belozer** [comment]
@miripiruni

**Comment by zxqfox** [comment]
Use 8.x © Cap

**Comment by miripiruni** [comment]
@belozer I think it’s because extend() [was fixed](https://github.com/bem/bem-xjst/issues/180) in v8.3.1.

Can you say exactly which version is "v7.x"? )

**Comment by miripiruni** [comment]
Please reopen issue if it’s still make sense.

**Comment by belozer** [comment]
@miripiruni 7.6.4

@zxqfox there is no possibility

**Comment by belozer** [comment]
The bug is not critical for us, at a cost in other ways.

**Comment by miripiruni** [comment]
@belozer we can port [commit](https://github.com/bem/bem-xjst/pull/363/files) to v7.x if it’s important.

**Comment by belozer** [comment]
@miripiruni ok ;)
