### ISSUE TITLE
Debug information, asserts, `include`

### ISSUE THREAD

**Issue by indutny** [bem/bem-xjst#49]
- Keep information about input source files (there could be multiple of them) #108 #136
- Consider adding `include`
- `lint` mode? With assertions for popular mistakes: https://github.com/bem/bemhint/issues/56
  - `.tag().def().content()`
  - `.def()(function() { /* forgot to return */ applyCtx({ ... }) })`
  - `block('b1')(tag()('a'))` should be `block('b1').tag()('a')`

**Comment by indutny** [comment]
Instead of `include` we could introduce sourcemap argument.

**Comment by indutny** [comment]
Asserts should use sourcemap to report errors in particular files.

**Comment by indutny** [comment]
Should also throw on: `mix({ ... })` instead of `mix()({ ... })`.

**Comment by arikon** [comment]
@indutny @veged What is `include`?

**Comment by veged** [comment]
we have `include` directive in older versions — it works so as you can imagine by semantic

**Comment by miripiruni** [comment]
v7.7.0 and v8.6.0
