### ISSUE TITLE
runtime-lint/index.js not found

### ISSUE THREAD

**Issue by baymer** [bem/bem-xjst#502]
### version
bem-xjst@7.7.6

### config

```(js)
// .enb/make.js
....
nodeConfig.addTechs([require('enb-bemxjst/techs/bemhtml'), {
    engineOptions: {
        runtimeLint: true,
    },
    filesTarget: '?.files'
}])
```
### build
`enb make projects/rubrics-v2017/desktop.bundles/rubrics --no-cache`

### build error
![image](https://user-images.githubusercontent.com/5292544/36494681-cb93fcbe-1743-11e8-890d-3eee71916f23.png)

PS: Because pwd is `~/nerpa`, but `~/nerpa/node_modules/bem-xjst/runtime-lint/index.js`.

**Comment by miripiruni** [comment]
+ bem-xjst@6.7.2

**Comment by miripiruni** [comment]
+ bem-xjst@7.7.7
