### ISSUE TITLE
Require of absent bundle file

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#51]
In **2.x** branch

Here https://github.com/bem/bem-xjst/blob/2.x/lib/bemhtml.js#L8 it waits for `bundle`, which is absent at https://github.com/bem/bem-xjst/tree/2.x/lib/bemhtml/runtime.

And as there's https://github.com/bem/bem-xjst/commit/3838318f3dcbb1b6d69bb4c76e3400a2a848c38b, it was done on purpose.

**Comment by indutny** [comment]
@tadatuta it fills automatically on `npm publish` or `make`.

**Comment by indutny** [comment]
I'd rather not commit it to the repo, because of the "diff-noise".
