### ISSUE TITLE
docs: Wrong default value for exportName in `3-api.md`

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#516]
See https://github.com/bem/bem-xjst/blob/e87712b1419b1b059b611908fa66513edae6cc7e/docs/ru/3-api.md#%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-exportname 

It says that default value for `exportName` is `BEMHTML`/`BEMTREE` but `bemhtml`/`bemtree` is exported instead.

PS: I'm not quite sure if it's just documentation issue. As far as I remember, it was really capital in `enb-bemxjst` for maybe we should decide to switch case in code instead of docs.

**Comment by miripiruni** [comment]
> PS: I'm not quite sure if it's just documentation issue. As far as I remember, it was really capital in enb-bemxjst for maybe we should decide to switch case in code instead of docs.

Me too. I’ll add `.toUpperCase()` for default case…

**Comment by miripiruni** [comment]
v8.9.3
