### ISSUE TITLE
attrescape: Do not escape &

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#533]
### Input code or something about issue background

https://goo.gl/TtGW5t

### Expected Behavior

`&` is not escaped

### Actual Behavior

`&` is escaped

### Possible Solution

Just drop `&` escaping for attrs

**Comment by miripiruni** [comment]
Do I need fix it in v7.x/v6.x/etc or in v8.x only?

**Comment by miripiruni** [comment]
HTML will decode entity from URL and make request with decoded url.

**Comment by miripiruni** [comment]
![image 2018-08-13 14 03 57](https://user-images.githubusercontent.com/144537/44028170-b910fe70-9f01-11e8-80ec-633d86ad4d18.jpg)
