### ISSUE TITLE
Benchmarks: missing dependencies, broken link in documentation

### ISSUE THREAD

**Issue by victor-homyakov** [bem/bem-xjst#538]
### Input code or something about issue background
I cannot run new benchmark test as described in https://github.com/bem/bem-xjst/blob/master/bench/README.md

`node runner.js --rev1 <hash1> --rev2 <hash2> --bemjson 1000`

### Expected Behavior
Test should run and produce some results, because README file states that
> dataPath and templatePath are optional

### Actual Behavior
Error in console:
```
Error: ENOENT: no such file or directory, scandir './node_modules/web-data/data'
```

Also link to https://github.com/miripiruni/web-data is dead

### Your Environment

bem-xjst version: current master

**Comment by tadatuta** [comment]
cc @miripiruni

**Comment by miripiruni** [comment]
@victor-homyakov web-data contains sensitive data. I move it: https://nda.ya.ru/3UZHV9

**Comment by victor-homyakov** [comment]
@miripiruni @tadatuta update documentation, please
