### ISSUE TITLE
Implement BEMTREE support

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#54]

**Comment by indutny** [comment]
Technical info: https://en.bem.info/technology/bemtree/v2/bemtree/

**Comment by tadatuta** [comment]
I'd be happy to have BEMTREE available in two modes: sync and async.

**Comment by tadatuta** [comment]
any news here?

**Comment by tadatuta** [comment]
any news?

**Comment by vithar** [comment]
I need bemtree in my project, do you have estimation to this task?

**Comment by tadatuta** [comment]
Implemented in https://github.com/bem/bem-xjst/pull/132
