### ISSUE TITLE
Option for custom naming

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#55]
Provide possibility to pass own naming scheme, e.g. with `bem-naming`

// cc @veged

**Comment by indutny** [comment]
May I ask you to expand on this a bit?

**Comment by tadatuta** [comment]
It's about possibility to change elems and mods delimiters (see https://github.com/bem/bem-xjst/blob/master/lib/bemhtml/runtime/utils.js#L6-L13).

Here is a [tool and documentation](https://github.com/bem/bem-naming#custom-naming-convention) on a subj. I do not insist on using `bem-naming` but at least on the same API to specify naming scheme:
```js
{
    elem: '__',
    mod: '_',
    wordPattern: '[a-zA-Z0-9-]+'
}
```

**Comment by veged** [comment]
I think two new options `modDelim` and `elemDelim` would be enough (we can't implement `wordPattern` anyway).

**Comment by tadatuta** [comment]
can we make it
```js
{
    naming: {
        elem: '__',
        mod: '_',
    }
}
```

It's quite important as we use `bem-naming` with such API everywhere.

**Comment by veged** [comment]
ok — :+1: for API consistency

**Comment by indutny** [comment]
Implemented, please give it a try!

**Comment by veged** [comment]
not `options.mod`/`options.elem` but `options.naming.mod`/`options.naming.elem`

**Comment by veged** [comment]
@tadatuta @blond we need to support this in `enb-bemxjst-2` or it's already should be available in `.enb/make.js`?

**Comment by tadatuta** [comment]
@veged I'll provide support tonight

**Comment by tadatuta** [comment]
@indutny the option works wrong:

```js
require('./').compile('', { naming: { elem: '$$', mod: '--' } }).apply({ block: 'b1', elem: 'e1'  });
```
results in
```html
'<div class="b1__e1"></div>'
```
but
```html
'<div class="b1$$e1"></div>'
```
expected.

Still `elem` partially works:
```js
require('./').compile('', { naming: { elem: '$$', mod: '--' } }).apply({ block: 'b1', elem: 'e1', elemMods: { m1: true }  });
```
results in
```html
'<div class="b1__e1 b1$$e1--m1"></div>'
```

**Comment by indutny** [comment]
Should be fixed now, sorry!

**Comment by voischev** [comment]
:fire:
