### ISSUE TITLE
replace() works wrong when grouped by predicate

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#57]
**Branch 2.x**
```js
block('b1').replace()(function () {
    return { block: 'b2' };
});
```
works fine (result is a string `<div class="b2"></div>`) but
```js
block('b1')(replace()(function () {
    return { block: 'b2' };
}));
```
doesn't apply templates on new context (result is an object `{ block: 'b2' }`).

**Comment by indutny** [comment]
Fixed in 21c05beaa8c31897334a77794b356978e42d3043, thank you!
