### ISSUE TITLE
Support includes for dev development

### ISSUE THREAD

**Issue by apsavin** [bem/bem-xjst#67]
We have dev mode now, which is pretty useful for debugging. But we can go further. Can we support includes?

Pros:
- no need to rebuild `bundle.bem{tree|html}.js` if no new files were created, only existing changed
- sweet debug messages and errors' stack traces

Cons:
- More complex code, yet another feature that needs support

cc @veged @indutny @tadatuta

**Comment by veged** [comment]
we gonna do something like this in [v2](https://github.com/bem/bem-xjst/tree/2.x)
