### ISSUE TITLE
Handle undefined as mix

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#69]
`bem-xjst` should handle `undefined` mixes as if there's just none. Otherwise templates fail here: https://github.com/bem/bem-xjst/blob/2.x/lib/bemhtml/runtime/index.js#L434 with `TypeError: Cannot read property 'block' of undefined`.

// cc @arikon @veged

**Comment by indutny** [comment]
Hm... isn't it a bug of the code that generates `mixes` array? How do they come there?

**Comment by tadatuta** [comment]
Maybe you are right but current stable version of bem-xjst handles it.

Here's one of the real life examples: https://nda.ya.ru/3Qr5ao

**Comment by indutny** [comment]
I guess we can handle it as well... I'm just a bit concerned about the performance of things, every extra check contributes negatively to it.

**Comment by indutny** [comment]
Fixed in b9ff3cb

**Comment by indutny** [comment]
Thank you!
