### ISSUE TITLE
Continuous Benchmarking

### ISSUE THREAD

**Issue by indutny** [bem/bem-xjst#85]
cc @veged 

I think something like http://arewefastyet.com/ would be great to have. It could be just cloning the repo on every commit, installing npm modules in its root and `bench` folder, and running:

`node bench/run.js --min-samples=500`

@veged do you think we have resources for this?

**Comment by veged** [comment]
sounds nice! can we use existing Travis infrastructure somehow? what resources are you talking about, time to develop runners and draw graphics?

**Comment by indutny** [comment]
@veged I was mostly talking about the server infrastructure ;) Drawing graphs should be easy.

I'll see how stable numbers will be if we'll run it on travis.

**Comment by miripiruni** [comment]
https://github.com/bem/bem-xjst/pull/308
