### ISSUE TITLE
bem-xjst@1.2.1: Strange reordering of array with apply()

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#86]
For BEMJSON `{ block: 'b1' }` and template
```js
block('b1').content()(function() {
    return [
        'first',
        apply('some-mode', {ctx: this.reapply({
            block: this.block,
            elem: 'elem1',
            content: 'second'
        })})
    ];
});
```
with `bem-xjst@1.2.1` the result is
```html
<div class="b1"><div class="b1__elem1">second</div>first</div>
```
but
```html
<div class="b1">first<div class="b1__elem1">second</div></div>
```
expected.

And it works as expected with `bem-xjst 4.0.1`.

**Comment by indutny** [comment]
Was it working fine before in 1.x?

**Comment by veged** [comment]
@tadatuta what exactly you try to do? why both `apply('some-mode'` and `this.reapply({`appear? looks like strange template...

**Comment by tadatuta** [comment]
That's really strange template from Islands library. I opened this issue because tests failed and was hard to understand why. I do not insist on a fix.

**Comment by veged** [comment]
can you point me exactly code in `islands`? perhaps it should be rewritten

**Comment by tadatuta** [comment]
It's already rewritten there.

**Comment by veged** [comment]
ok then ;-)
