### ISSUE TITLE
mods field in BEMJSON should not be treated as elemMods

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#88]
For BEMJSON `{ block: 'b1', elem: 'e1', mods: { m1: 'v1' } }` with default templates the result is
`<div class="b1__e1 b1__e1_m1_v1"></div>` but it should be `<div class="b1__e1"></div>`.

That'll break backward compatibility (with all previous implementations) so it should be major version.

For discussion please refer to https://github.com/bem/bem-core/issues/1026#issuecomment-128480156

// cc @veged @narqo

**Comment by arikon** [comment]
Consider to delay because of major changes that will make us to rewrite a lot of existing code in web services.

**Comment by zxqfox** [comment]
@arikon Am I right that web services using `{ mods: ... }` as `{ elemMods: ... }` in `bemjson`?

**Comment by zxqfox** [comment]
Guess, there is the same problem with `{ block: 'b1', elemMods: { m: 'v' } }` (`<div class="b1 b1_m_v"></div>`).

https://github.com/bem/bem-xjst/blob/master/test/tree-test.js#L169-L176

**Comment by arikon** [comment]
@zxqfox Yes, you are. Some of them are using `mods` instead of `elemMods`.
