### ISSUE TITLE
Make apply() polymorphic

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#91]
WARN: I'm not sure if it's a good idea!

`bem-xjst@1.x` understands that if the only argument for `apply()` is an object that means changes but not a mode. I suggest to support the same thing for `bem-xjst@4.x` but there's a difference that there's no empty mode anymore and as so `default` should be used.

**Comment by indutny** [comment]
I don't really like it that much, everything is either monomorphic or very shallow polymorphic in bem-xjst@4.x at the moment.

Maybe @veged has more to say.

**Comment by indutny** [comment]
Feel free to reopen if you think that this should be fixed.
