### ISSUE TITLE
mix() works wrong if literal is passed

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-xjst#92]
`bem-xjst@4.0.1`

BEMJSON:
```js
[
    {
        block: 'b1',
        mods: { m1: 'v1' }
    },
    {
        block: 'b1',
        mods: { ololo: 'trololo' }
    }
]
```
Templates:
```js
block('b1').mix()([{ block: 'b2' }]);
// block('b1').mix()(function() { return [{ block: 'b2' }]; }); // will work fine if you replace previous line with this one

block('b1').mod('m1', 'v1')(
    mix()(function() {
        var mix = applyNext() || [];
        mix.push({ mods: { m2: 'v2' } });

        return mix;
    })
);
```
Results in unexpected `b1_m2_v2` mix on second block without `b1_m1_v1`:
```html
<div class="b1 b1_m1_v1 b2 b1_m2_v2"></div>
<div class="b1 b1_ololo_trololo b2 b1_m2_v2"></div>
```

`bem-xjst@1.x` works fine with both variants.

**Comment by indutny** [comment]
What else did you expect? :) You are changing the array passed by reference. Creating a copy might be expensive. I suggest using `.slice()` in such blocks.

**Comment by tadatuta** [comment]
well, that's kinda not obvious at least because on previous version the same code worked fine :(

**Comment by indutny** [comment]
@tadatuta I bet it wasn't working that fine with dev mode ;) It is just the production mode that was cloning the JSON for you by transforming literal value into the function returning it.

**Comment by veged** [comment]
We can automatically clone all non-functions values that passed at least to `mix`, `content`, `attrs` modes. But it may cause significant performance overhead in cases when a lot of "literals" are used as content. Also, there are may be some cases when you expect to use same value by reference. So I can't calmly say "let's do it" :-/

In addition I think we should introduce some helpers for cases like "add mixes" so we doesn't need to do:
```js
var mix = applyNext() || [];
mix.push({ mods: { m2: 'v2' } });
return mix;
```
We can have `block('b1').mod('m1', 'v1').addMix()({ mods : { m2 : 'v2' } })` as syntax sugar for:
```js
block('b1').mod('m1', 'v1').mix()(function() {
    return (applyNext() || []).concat({ mods: { m2: 'v2' } });
})
```

**Comment by veged** [comment]
@tadatuta I suggest consider this issue as "won't fix" since previously it's already works inconsistent between dev and prod mode. And create new one about `addMix` syntax sugar.

**Comment by zxqfox** [comment]
:+1: for wontfix, but... Can we throw if someone puts there an object? What do you think about some real life use cases for that usage (w/o function)?

**Comment by veged** [comment]
the problem not in passing literals to `mix` but in modifying such literals with other templates — so I can't agree that we should deny passing literals itself
