### ISSUE TITLE
combine 2 compiled BEMHTML objects

### ISSUE THREAD

**Issue by Guria** [bem/bem-xjst#94]
I know about new `.compile()` method, but it requires original templates as string on client side.
Just curious if something like `BEMHTML.extend(anotherBEMHTML)` is able to implement. In case of ymodules it could look like 
```js
modules.define('BEMHTML', function(provide, BEMHTML){
  var anotherBEMHTML = {
    /* ... */
  };
  provide(BEMHTML.extend(anotherBEMHTML));
});
```

**Comment by indutny** [comment]
`.compile()` does not require original templates. You may use it to add more templates to existing BEMHTML instance.

**Comment by Guria** [comment]
I mean it requires templates of anotherBEMHTML object.

**Comment by indutny** [comment]
Aaah, this is what you meant. I think we can do it too. But what is the point? Distributing templates with runtime is a waste of bandwidth.

**Comment by tadatuta** [comment]
I agree it's not very useful feature as we always can build bundle of just concatenated templates before compilation.

**Comment by Guria** [comment]
Exactly. That why I curious if we can just extend one compiled object with another.
Use case could be to allow dist versions of separate packages (eg, bem-calendar or bem-forms) could be loaded after dist version of bem-components and it will just works.
Server-side concatenation before compilation is good point, but you have to setup it. Including two js files doesn't need such complexity on the other hand.

**Comment by indutny** [comment]
@Guria current runtime bundle is about 40kb uncompressed. Are you sure that you would rather load it a couple of times, than distribute both sources and compiled files?
