### ISSUE TITLE
`elem('*')`

### ISSUE THREAD

**Issue by veged** [bem/bem-xjst#95]
We need analog `block('*')` matcher for elements: `elem('*')`.

**Comment by indutny** [comment]
@veged this is going to slow things down a lot... I'll need to do two lookups instead of one to check the `elem('*')`.

How necessary is this? Could it be worked around?

**Comment by veged** [comment]
It's needed for functionality that can be bind to all BEM-entities (i.e. analog of `match(this.ctx._myCustomField)` without `block`). Why we need two lookups in case when `this.elem === undefined` (`elem('*')` doesn't need to be checked)? In case `this.elem !== undefined` vice versa — `block('*')` doesn't need to be checked.

**Comment by indutny** [comment]
Nevermind, figured out how to do it without extra lookups. PTAL at how it works in 4.1.0 ;)

**Comment by veged** [comment]
cool! ;-)

can you point me exactly what I need to review? https://github.com/bem/bem-xjst/commit/6cb6f3b22601aa29680267d85b71288d0fc076e3#diff-958f90d6d94bb3ea244d8d1787058c15R681 looks good from quick view

**Comment by indutny** [comment]
Yep that was it ;)

**Comment by indutny** [comment]
Thanks!
