### ISSUE TITLE
Независимая сборка

### ISSUE THREAD

**Issue by voischev** [bem/bem-xjst#98]
Очень хочется `bemhtml` собирать любым способом.

Например
```
var template = bem.compile([
    require(‘./b1.bemhtml’), 
    require(‘./b2.bemhtml’), 
    require(‘./b3.bemhtml')
]);

template.apply({ block: 'b1', content: [{ block: 'b2'}, { block: 'b3' }]});
```

Так же кажется, что для нормального использования на клиенте мешает `vm`? Зачем для исполнения шаблонов новый контекст?  И само собой хочется делать так:

```
module.exports = function() {
    return block('b6').content(function() {
        return require('moment')(this.ctx.date);
    });
} 
```
Ни хочется ли вам нам руки развязать? Пойдем куда нибудь с этими замечательными технологиями завоевывать дисковое пространство приложений))

**Comment by awinogradov** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by voischev** [comment]
сс/ @veged @blond @tadatuta @zxqfox

**Comment by tadatuta** [comment]
Давайте голосом это обсудим, кажется, что в первой части ты хочешь чего-то странного, а во второй — то, что изначально работает ;)

**Comment by tadatuta** [comment]
@voischev @awinogradov  Закрываем?

**Comment by awinogradov** [comment]
Да, обсудили голосом.

**Comment by voischev** [comment]
:+1:
